(function(){
  "use strict";

  const VERSION = "PMS-V136-OPERATIONAL-WEEK-CALENDAR";
  const PAGE = "operativo";
  const LANGS = ["IT", "EN", "RO", "AR"];
  const WEEKDAYS = {
    IT: ["Lunedi", "Martedi", "Mercoledi", "Giovedi", "Venerdi", "Sabato", "Domenica"],
    EN: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
    RO: ["Luni", "Marti", "Miercuri", "Joi", "Vineri", "Sambata", "Duminica"],
    AR: ["\u0627\u0644\u0627\u062b\u0646\u064a\u0646", "\u0627\u0644\u062b\u0644\u0627\u062b\u0627\u0621", "\u0627\u0644\u0627\u0631\u0628\u0639\u0627\u0621", "\u0627\u0644\u062e\u0645\u064a\u0633", "\u0627\u0644\u062c\u0645\u0639\u0629", "\u0627\u0644\u0633\u0628\u062a", "\u0627\u0644\u0627\u062d\u062f"]
  };
  const TEXT = {
    IT: {
      title: "Gestione operativa settimanale",
      subtitle: "Programma carichi da ordini e intermediazioni",
      prev: "Settimana precedente",
      next: "Settimana successiva",
      today: "Oggi",
      printWeek: "Stampa settimana",
      printAll: "Stampa tutto",
      printLanguage: "Lingua stampa",
      orders: "Ordini",
      deals: "Intermediazioni",
      unscheduledOrders: "Ordini da programmare",
      unscheduledDeals: "Intermediazioni da programmare",
      noItems: "Nessun viaggio programmato",
      noBacklog: "Nessun elemento da programmare",
      tapHint: "Tocca una scheda e poi il giorno, oppure trascinala nel calendario.",
      removeDate: "Togli data",
      client: "Cliente",
      supplier: "Fornitore",
      product: "Prodotto",
      quantity: "Quantita",
      status: "Stato",
      loadDate: "Data carico",
      week: "Settimana",
      generated: "Generato da Parmitalia Management System",
      allOperationalPrint: "Stampa operativa completa",
      backlog: "Da programmare",
      type: "Tipo",
      menuLabel: "Gestione operativa",
      scheduleField: "Data carico / programma",
      notesField: "Note programma"
    },
    EN: {
      title: "Weekly operational planning",
      subtitle: "Loading schedule from orders and intermediations",
      prev: "Previous week",
      next: "Next week",
      today: "Today",
      printWeek: "Print week",
      printAll: "Print all",
      printLanguage: "Print language",
      orders: "Orders",
      deals: "Intermediations",
      unscheduledOrders: "Orders to schedule",
      unscheduledDeals: "Intermediations to schedule",
      noItems: "No trip scheduled",
      noBacklog: "Nothing to schedule",
      tapHint: "Tap one card and then the day, or drag it into the calendar.",
      removeDate: "Clear date",
      client: "Customer",
      supplier: "Supplier",
      product: "Product",
      quantity: "Quantity",
      status: "Status",
      loadDate: "Loading date",
      week: "Week",
      generated: "Generated by Parmitalia Management System",
      allOperationalPrint: "Complete operational print",
      backlog: "To schedule",
      type: "Type",
      menuLabel: "Operations",
      scheduleField: "Loading / schedule date",
      notesField: "Schedule notes"
    },
    RO: {
      title: "Planificare operationala saptamanala",
      subtitle: "Program incarcare din comenzi si intermedieri",
      prev: "Saptamana precedenta",
      next: "Saptamana urmatoare",
      today: "Azi",
      printWeek: "Printeaza saptamana",
      printAll: "Printeaza tot",
      printLanguage: "Limba printare",
      orders: "Comenzi",
      deals: "Intermedieri",
      unscheduledOrders: "Comenzi de programat",
      unscheduledDeals: "Intermedieri de programat",
      noItems: "Nicio cursa programata",
      noBacklog: "Nimic de programat",
      tapHint: "Atinge o fisa si apoi ziua, sau trage fisa in calendar.",
      removeDate: "Sterge data",
      client: "Client",
      supplier: "Furnizor",
      product: "Produs",
      quantity: "Cantitate",
      status: "Stare",
      loadDate: "Data incarcare",
      week: "Saptamana",
      generated: "Generat de Parmitalia Management System",
      allOperationalPrint: "Print operational complet",
      backlog: "De programat",
      type: "Tip",
      menuLabel: "Gestiune operationala",
      scheduleField: "Data incarcare / program",
      notesField: "Note program"
    },
    AR: {
      title: "\u0627\u0644\u062a\u062e\u0637\u064a\u0637 \u0627\u0644\u062a\u0634\u063a\u064a\u0644\u064a \u0627\u0644\u0627\u0633\u0628\u0648\u0639\u064a",
      subtitle: "\u062c\u062f\u0648\u0644 \u0627\u0644\u062a\u062d\u0645\u064a\u0644 \u0645\u0646 \u0627\u0644\u0637\u0644\u0628\u0627\u062a \u0648\u0627\u0644\u0648\u0633\u0627\u0637\u0629",
      prev: "\u0627\u0644\u0627\u0633\u0628\u0648\u0639 \u0627\u0644\u0633\u0627\u0628\u0642",
      next: "\u0627\u0644\u0627\u0633\u0628\u0648\u0639 \u0627\u0644\u062a\u0627\u0644\u064a",
      today: "\u0627\u0644\u064a\u0648\u0645",
      printWeek: "\u0637\u0628\u0627\u0639\u0629 \u0627\u0644\u0627\u0633\u0628\u0648\u0639",
      printAll: "\u0637\u0628\u0627\u0639\u0629 \u0627\u0644\u0643\u0644",
      printLanguage: "\u0644\u063a\u0629 \u0627\u0644\u0637\u0628\u0627\u0639\u0629",
      orders: "\u0627\u0644\u0637\u0644\u0628\u0627\u062a",
      deals: "\u0627\u0644\u0648\u0633\u0627\u0637\u0629",
      unscheduledOrders: "\u0637\u0644\u0628\u0627\u062a \u0644\u0644\u062c\u062f\u0648\u0644\u0629",
      unscheduledDeals: "\u0648\u0633\u0627\u0637\u0629 \u0644\u0644\u062c\u062f\u0648\u0644\u0629",
      noItems: "\u0644\u0627 \u062a\u0648\u062c\u062f \u0631\u062d\u0644\u0629 \u0645\u062c\u062f\u0648\u0644\u0629",
      noBacklog: "\u0644\u0627 \u064a\u0648\u062c\u062f \u0639\u0646\u0635\u0631 \u0644\u0644\u062c\u062f\u0648\u0644\u0629",
      tapHint: "\u0627\u062e\u062a\u0631 \u0628\u0637\u0627\u0642\u0629 \u062b\u0645 \u0627\u0644\u064a\u0648\u0645\u060c \u0627\u0648 \u0627\u0633\u062d\u0628\u0647\u0627 \u0627\u0644\u0649 \u0627\u0644\u062a\u0642\u0648\u064a\u0645.",
      removeDate: "\u062d\u0630\u0641 \u0627\u0644\u062a\u0627\u0631\u064a\u062e",
      client: "\u0627\u0644\u0639\u0645\u064a\u0644",
      supplier: "\u0627\u0644\u0645\u0648\u0631\u062f",
      product: "\u0627\u0644\u0645\u0646\u062a\u062c",
      quantity: "\u0627\u0644\u0643\u0645\u064a\u0629",
      status: "\u0627\u0644\u062d\u0627\u0644\u0629",
      loadDate: "\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u062a\u062d\u0645\u064a\u0644",
      week: "\u0627\u0644\u0627\u0633\u0628\u0648\u0639",
      generated: "\u062a\u0645 \u0627\u0646\u0634\u0627\u0624\u0647 \u0628\u0648\u0627\u0633\u0637\u0629 Parmitalia Management System",
      allOperationalPrint: "\u0637\u0628\u0627\u0639\u0629 \u062a\u0634\u063a\u064a\u0644\u064a\u0629 \u0643\u0627\u0645\u0644\u0629",
      backlog: "\u0644\u0644\u062c\u062f\u0648\u0644\u0629",
      type: "\u0627\u0644\u0646\u0648\u0639",
      menuLabel: "\u0627\u0644\u0627\u062f\u0627\u0631\u0629 \u0627\u0644\u062a\u0634\u063a\u064a\u0644\u064a\u0629",
      scheduleField: "\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u062a\u062d\u0645\u064a\u0644 / \u0627\u0644\u062c\u062f\u0648\u0644\u0629",
      notesField: "\u0645\u0644\u0627\u062d\u0638\u0627\u062a \u0627\u0644\u062c\u062f\u0648\u0644\u0629"
    }
  };

  let selectedCard = null;

  function appState(){
    window.state = window.state || {};
    state.settings = state.settings || {};
    if (!Array.isArray(state.orders)) state.orders = [];
    if (!Array.isArray(state.intermediations)) state.intermediations = [];
    return state;
  }
  function esc(value){
    return String(value == null ? "" : value).replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  }
  function lang(kind){
    const settings = appState().settings;
    const code = kind === "print" ? (settings.printLanguage || settings.appLanguage) : settings.appLanguage;
    return LANGS.includes(code) ? code : "IT";
  }
  function L(key, code){
    const pack = TEXT[code || lang()] || TEXT.IT;
    return pack[key] || TEXT.IT[key] || key;
  }
  function saveLocal(){
    try {
      if (typeof save === "function") return save();
      if (typeof STORAGE_KEY !== "undefined") localStorage.setItem(STORAGE_KEY, JSON.stringify(appState()));
    } catch(error) {
      console.warn(VERSION + " save failed", error);
    }
  }
  function isoDate(date){
    const d = new Date(date);
    d.setHours(12, 0, 0, 0);
    return d.getFullYear() + "-" + String(d.getMonth() + 1).padStart(2, "0") + "-" + String(d.getDate()).padStart(2, "0");
  }
  function parseIso(value){
    if (!value) return null;
    const parts = String(value).slice(0, 10).split("-").map(Number);
    if (parts.length !== 3 || parts.some(n => !Number.isFinite(n))) return null;
    return new Date(parts[0], parts[1] - 1, parts[2], 12, 0, 0, 0);
  }
  function mondayOf(value){
    const d = parseIso(value) || new Date();
    d.setHours(12, 0, 0, 0);
    const day = d.getDay() || 7;
    d.setDate(d.getDate() - day + 1);
    return isoDate(d);
  }
  function addDays(value, days){
    const d = parseIso(value) || new Date();
    d.setDate(d.getDate() + days);
    return isoDate(d);
  }
  function weekStart(){
    const settings = appState().settings;
    settings.pms136WeekStart = mondayOf(settings.pms136WeekStart || isoDate(new Date()));
    return settings.pms136WeekStart;
  }
  function weekDays(){
    const start = weekStart();
    return Array.from({length: 7}, (_, index) => addDays(start, index));
  }
  function formatDate(value, code){
    const d = parseIso(value);
    if (!d) return "-";
    const locale = code === "EN" ? "en-GB" : code === "RO" ? "ro-RO" : code === "AR" ? "ar" : "it-IT";
    return d.toLocaleDateString(locale, {day:"2-digit", month:"2-digit", year:"numeric"});
  }
  function orderCode(item){
    return item.code || item.orderCode || item.id || "-";
  }
  function dealCode(item){
    return item.code || item.id || "-";
  }
  function itemTitle(type, item){
    return type === "order" ? orderCode(item) : dealCode(item);
  }
  function routeLine(item){
    const bits = [
      item.loadingPlace || item.pickupPlace || item.origin || item.from,
      item.deliveryPlace || item.destination || item.to
    ].filter(Boolean);
    return bits.length ? bits.join(" -> ") : "";
  }
  function itemMeta(item, code){
    const qty = [item.quantity, item.unit].filter(Boolean).join(" ");
    const rows = [
      [L("client", code), item.client || item.customer || item.targetClient],
      [L("supplier", code), item.supplier],
      [L("product", code), item.product || item.productName],
      [L("quantity", code), qty],
      [L("status", code), item.status]
    ].filter(row => row[1]);
    const route = routeLine(item);
    if (route) rows.push([L("loadDate", code), route]);
    return rows;
  }
  function scheduledDate(item){
    return String(item.scheduledDate || item.operationalDate || "").slice(0, 10);
  }
  function allItems(){
    const st = appState();
    const orders = st.orders.map(item => ({type:"order", item}));
    const deals = st.intermediations.map(item => ({type:"deal", item}));
    return orders.concat(deals);
  }
  function findItem(type, id){
    const list = type === "order" ? appState().orders : appState().intermediations;
    return list.find(item => String(item.id || item.code || item.orderCode) === String(id));
  }
  function cardId(type, item){
    return String(item.id || item.code || item.orderCode || "");
  }
  function optionHtml(selected){
    return LANGS.map(code => '<option value="' + code + '"' + (selected === code ? " selected" : "") + ">" + code + "</option>").join("");
  }
  function renderCard(type, item, compact){
    const code = lang();
    const id = cardId(type, item);
    const rows = itemMeta(item, code).slice(0, compact ? 3 : 5);
    const badge = type === "order" ? L("orders", code) : L("deals", code);
    return `
      <article class="pms136-card" draggable="true" tabindex="0" data-pms136-type="${esc(type)}" data-pms136-id="${esc(id)}">
        <div class="pms136-card-head">
          <strong>${esc(itemTitle(type, item))}</strong>
          <span>${esc(badge)}</span>
        </div>
        ${rows.map(row => `<div class="pms136-card-row"><b>${esc(row[0])}</b><span>${esc(row[1])}</span></div>`).join("")}
        ${scheduledDate(item) ? `<button type="button" class="pms136-clear" data-pms136-clear="${esc(type)}" data-pms136-id="${esc(id)}">${esc(L("removeDate", code))}</button>` : ""}
      </article>`;
  }
  function itemsForDay(day){
    return allItems().filter(entry => scheduledDate(entry.item) === day);
  }
  function unscheduled(type){
    const list = type === "order" ? appState().orders : appState().intermediations;
    return list.filter(item => !scheduledDate(item));
  }
  function renderDay(day, index){
    const code = lang();
    const entries = itemsForDay(day);
    return `
      <section class="pms136-day" data-pms136-day="${esc(day)}">
        <header>
          <strong>${esc((WEEKDAYS[code] || WEEKDAYS.IT)[index])}</strong>
          <span>${esc(formatDate(day, code))}</span>
        </header>
        <div class="pms136-day-list">
          ${entries.length ? entries.map(entry => renderCard(entry.type, entry.item, true)).join("") : `<div class="pms136-empty">${esc(L("noItems", code))}</div>`}
        </div>
      </section>`;
  }
  function renderBacklog(type){
    const code = lang();
    const list = unscheduled(type);
    const title = type === "order" ? L("unscheduledOrders", code) : L("unscheduledDeals", code);
    return `
      <section class="pms136-backlog" data-pms136-backlog="${esc(type)}">
        <header><h3>${esc(title)}</h3><span>${list.length}</span></header>
        <div class="pms136-backlog-list">
          ${list.length ? list.map(item => renderCard(type, item, false)).join("") : `<div class="pms136-empty">${esc(L("noBacklog", code))}</div>`}
        </div>
      </section>`;
  }
  function renderPlanner(){
    const code = lang();
    const printCode = lang("print");
    const days = weekDays();
    return `
      <div class="pms136-page" dir="${code === "AR" ? "rtl" : "ltr"}">
        <div class="pms136-toolbar">
          <div>
            <h2>${esc(L("title", code))}</h2>
            <p>${esc(L("subtitle", code))}</p>
          </div>
          <div class="pms136-actions">
            <button type="button" class="secondary-button" data-pms136-week="-7">${esc(L("prev", code))}</button>
            <button type="button" class="secondary-button" data-pms136-today>${esc(L("today", code))}</button>
            <button type="button" class="secondary-button" data-pms136-week="7">${esc(L("next", code))}</button>
            <label>${esc(L("printLanguage", code))}
              <select id="pms136-print-lang" class="pms135-print-lang">${optionHtml(printCode)}</select>
            </label>
            <button type="button" class="primary-button" data-pms136-print-week>${esc(L("printWeek", code))}</button>
            <button type="button" class="secondary-button" data-pms136-print-all>${esc(L("printAll", code))}</button>
          </div>
        </div>
        <div class="pms136-hint">${esc(L("tapHint", code))}</div>
        <div class="pms136-week-label">${esc(L("week", code))}: ${esc(formatDate(days[0], code))} - ${esc(formatDate(days[6], code))}</div>
        <div class="pms136-calendar">
          ${days.map(renderDay).join("")}
        </div>
        <div class="pms136-backlogs">
          ${renderBacklog("order")}
          ${renderBacklog("deal")}
        </div>
      </div>`;
  }
  function setScheduled(type, id, day){
    const item = findItem(type, id);
    if (!item) return false;
    item.scheduledDate = day || "";
    item.operationalDate = item.scheduledDate;
    saveLocal();
    return true;
  }
  function rerenderPlanner(){
    const content = document.getElementById("content");
    if (content) content.innerHTML = renderPlanner();
    bindPlannerActions();
  }
  function dragDataFromCard(card){
    return card ? {type: card.dataset.pms136Type, id: card.dataset.pms136Id} : null;
  }
  function setSelected(card){
    document.querySelectorAll(".pms136-card.is-selected").forEach(el => el.classList.remove("is-selected"));
    selectedCard = dragDataFromCard(card);
    if (card) card.classList.add("is-selected");
  }
  function bindPlannerActions(){
    const root = document.querySelector(".pms136-page");
    if (!root) return;
    root.querySelectorAll("[data-pms136-week]").forEach(button => {
      button.onclick = () => {
        appState().settings.pms136WeekStart = mondayOf(addDays(weekStart(), Number(button.dataset.pms136Week || 0)));
        saveLocal();
        rerenderPlanner();
      };
    });
    const todayButton = root.querySelector("[data-pms136-today]");
    if (todayButton) todayButton.onclick = () => {
      appState().settings.pms136WeekStart = mondayOf(isoDate(new Date()));
      saveLocal();
      rerenderPlanner();
    };
    const printSelect = root.querySelector("#pms136-print-lang");
    if (printSelect) printSelect.onchange = () => {
      appState().settings.printLanguage = printSelect.value;
      const top = document.getElementById("pms134-print-lang");
      if (top) top.value = printSelect.value;
      saveLocal();
    };
    root.querySelectorAll(".pms136-card").forEach(card => {
      card.addEventListener("dragstart", event => {
        const data = dragDataFromCard(card);
        event.dataTransfer.setData("application/x-pms136", JSON.stringify(data));
        event.dataTransfer.effectAllowed = "move";
        setSelected(card);
      });
      card.addEventListener("click", event => {
        if (event.target.closest("button")) return;
        setSelected(card);
      });
      card.addEventListener("keydown", event => {
        if (event.key === "Enter" || event.key === " ") {
          event.preventDefault();
          setSelected(card);
        }
      });
    });
    root.querySelectorAll(".pms136-day").forEach(dayNode => {
      dayNode.addEventListener("dragover", event => {
        event.preventDefault();
        dayNode.classList.add("is-over");
      });
      dayNode.addEventListener("dragleave", () => dayNode.classList.remove("is-over"));
      dayNode.addEventListener("drop", event => {
        event.preventDefault();
        dayNode.classList.remove("is-over");
        let data = selectedCard;
        try { data = JSON.parse(event.dataTransfer.getData("application/x-pms136")) || data; } catch(error) {}
        if (data && setScheduled(data.type, data.id, dayNode.dataset.pms136Day)) rerenderPlanner();
      });
      dayNode.addEventListener("click", event => {
        if (event.target.closest(".pms136-card,button")) return;
        if (selectedCard && setScheduled(selectedCard.type, selectedCard.id, dayNode.dataset.pms136Day)) {
          selectedCard = null;
          rerenderPlanner();
        }
      });
    });
    root.querySelectorAll("[data-pms136-clear]").forEach(button => {
      button.onclick = event => {
        event.stopPropagation();
        if (setScheduled(button.dataset.pms136Clear, button.dataset.pms136Id, "")) rerenderPlanner();
      };
    });
    const printWeek = root.querySelector("[data-pms136-print-week]");
    if (printWeek) printWeek.onclick = () => printOperational(false);
    const printAll = root.querySelector("[data-pms136-print-all]");
    if (printAll) printAll.onclick = () => printOperational(true);
  }
  function printRowsForDay(day, code){
    const rows = itemsForDay(day);
    if (!rows.length) return '<tr><td colspan="6">' + esc(L("noItems", code)) + '</td></tr>';
    return rows.map(entry => {
      const item = entry.item;
      return '<tr>' +
        '<td>' + esc(entry.type === "order" ? L("orders", code) : L("deals", code)) + '</td>' +
        '<td>' + esc(itemTitle(entry.type, item)) + '</td>' +
        '<td>' + esc(item.client || item.customer || item.targetClient || "-") + '</td>' +
        '<td>' + esc(item.supplier || "-") + '</td>' +
        '<td>' + esc(item.product || item.productName || "-") + '</td>' +
        '<td>' + esc([item.quantity, item.unit].filter(Boolean).join(" ") || item.status || "-") + '</td>' +
      '</tr>';
    }).join("");
  }
  function printBacklogRows(type, code){
    const list = unscheduled(type);
    if (!list.length) return '<tr><td colspan="5">' + esc(L("noBacklog", code)) + '</td></tr>';
    return list.map(item => '<tr>' +
      '<td>' + esc(itemTitle(type, item)) + '</td>' +
      '<td>' + esc(item.client || item.customer || item.targetClient || "-") + '</td>' +
      '<td>' + esc(item.supplier || "-") + '</td>' +
      '<td>' + esc(item.product || item.productName || "-") + '</td>' +
      '<td>' + esc(item.status || "-") + '</td>' +
    '</tr>').join("");
  }
  function printOperational(includeBacklog){
    const code = lang("print");
    const select = document.getElementById("pms136-print-lang");
    if (select && LANGS.includes(select.value)) {
      appState().settings.printLanguage = select.value;
      saveLocal();
    }
    const days = weekDays();
    const dir = code === "AR" ? "rtl" : "ltr";
    const daySections = days.map((day, index) => `
      <h2>${esc((WEEKDAYS[code] || WEEKDAYS.IT)[index])} - ${esc(formatDate(day, code))}</h2>
      <table class="print-table">
        <thead><tr><th>${esc(L("type", code))}</th><th>ID</th><th>${esc(L("client", code))}</th><th>${esc(L("supplier", code))}</th><th>${esc(L("product", code))}</th><th>${esc(L("quantity", code))}</th></tr></thead>
        <tbody>${printRowsForDay(day, code)}</tbody>
      </table>`).join("");
    const backlog = includeBacklog ? `
      <h2>${esc(L("backlog", code))} - ${esc(L("orders", code))}</h2>
      <table class="print-table"><thead><tr><th>ID</th><th>${esc(L("client", code))}</th><th>${esc(L("supplier", code))}</th><th>${esc(L("product", code))}</th><th>${esc(L("status", code))}</th></tr></thead><tbody>${printBacklogRows("order", code)}</tbody></table>
      <h2>${esc(L("backlog", code))} - ${esc(L("deals", code))}</h2>
      <table class="print-table"><thead><tr><th>ID</th><th>${esc(L("client", code))}</th><th>${esc(L("supplier", code))}</th><th>${esc(L("product", code))}</th><th>${esc(L("status", code))}</th></tr></thead><tbody>${printBacklogRows("deal", code)}</tbody></table>` : "";
    const title = includeBacklog ? L("allOperationalPrint", code) : L("title", code);
    const html = `
      <div class="print-document pms136-print" dir="${dir}" lang="${code.toLowerCase()}">
        <div class="print-header">
          <div><h1>${esc(title)}</h1><strong>${esc(appState().settings.legalName || "PARMITALIA DISTRIBUTION SRL")}</strong></div>
          <div class="print-meta">${esc(L("week", code))}: ${esc(formatDate(days[0], code))} - ${esc(formatDate(days[6], code))}</div>
        </div>
        ${daySections}
        ${backlog}
        <div class="print-footer">${esc(L("generated", code))}</div>
      </div>`;
    if (typeof openPrint === "function") openPrint(html);
  }
  function ensureModule(){
    if (typeof modules !== "undefined" && Array.isArray(modules)) {
      const existing = modules.find(item => item.id === PAGE);
      if (existing) {
        existing.label = L("menuLabel");
        existing.subtitle = L("subtitle");
        return;
      }
      const index = modules.findIndex(item => item.id === "dashboard");
      modules.splice(index >= 0 ? index + 1 : modules.length, 0, {
        id: PAGE,
        label: L("menuLabel"),
        subtitle: L("subtitle"),
        roles: ["admin", "assistant"]
      });
    }
  }
  function upsertField(module, key, def, afterKeys){
    if (typeof schemas === "undefined") return;
    schemas[module] = schemas[module] || {title: module, fields: []};
    const fields = Array.isArray(schemas[module].fields) ? schemas[module].fields : [];
    const found = fields.find(item => item.key === key);
    if (found) Object.assign(found, def, {key});
    else {
      const after = (afterKeys || []).map(k => fields.findIndex(item => item.key === k)).filter(i => i >= 0).pop();
      fields.splice(after >= 0 ? after + 1 : fields.length, 0, Object.assign({key}, def));
    }
    schemas[module].fields = fields;
  }
  function ensureSchemaFields(){
    upsertField("orders", "scheduledDate", {label: TEXT.IT.scheduleField, type: "date"}, ["expectedDelivery", "deliveryDate", "requestDate", "date"]);
    upsertField("orders", "scheduledNotes", {label: TEXT.IT.notesField, type: "textarea", full: true}, ["scheduledDate"]);
    upsertField("intermediations", "scheduledDate", {label: TEXT.IT.scheduleField, type: "date"}, ["targetDate", "dueDate", "date"]);
    upsertField("intermediations", "scheduledNotes", {label: TEXT.IT.notesField, type: "textarea", full: true}, ["scheduledDate"]);
  }
  function injectCss(){
    let style = document.getElementById("pms-v136-style");
    if (!style) {
      style = document.createElement("style");
      style.id = "pms-v136-style";
      document.head.appendChild(style);
    }
    style.textContent = `
      .pms136-page{display:flex;flex-direction:column;gap:12px;color:#1f2933}
      .pms136-toolbar{display:flex;align-items:flex-start;justify-content:space-between;gap:16px;background:#fff;border:1px solid #dfe5ea;border-radius:8px;padding:14px;box-shadow:0 3px 12px rgba(30,45,60,.045)}
      .pms136-toolbar h2{margin:0;color:#25384a;font-size:18px;letter-spacing:0;text-transform:uppercase}
      .pms136-toolbar p{margin:4px 0 0;color:#6b7682;font-size:12px}
      .pms136-actions{display:flex;align-items:end;justify-content:flex-end;gap:8px;flex-wrap:wrap}
      .pms136-actions button{width:auto!important;margin:0!important;white-space:nowrap}
      .pms136-actions label{display:grid;gap:4px;color:#5e6b77;font-size:10px;font-weight:800;text-transform:uppercase}
      .pms136-actions select{height:34px;min-width:72px}
      .pms136-hint,.pms136-week-label{border:1px solid #dfe5ea;background:#fbfcfd;color:#445565;border-radius:8px;padding:9px 11px;font-size:12px;font-weight:700}
      .pms136-week-label{background:#eef3f6;color:#25384a}
      .pms136-calendar{display:grid;grid-template-columns:repeat(7,minmax(132px,1fr));gap:8px;min-height:420px}
      .pms136-day{display:flex;flex-direction:column;min-height:420px;background:#fff;border:1px solid #dfe5ea;border-radius:8px;overflow:hidden}
      .pms136-day.is-over{border-color:#91a3b4;background:#f6f9fb}
      .pms136-day header{display:grid;gap:2px;padding:10px;border-bottom:1px solid #dfe5ea;background:#f4f7f9}
      .pms136-day header strong{font-size:12px;color:#25384a;text-transform:uppercase}
      .pms136-day header span{font-size:11px;color:#6b7682}
      .pms136-day-list{display:flex;flex-direction:column;gap:7px;padding:8px;flex:1}
      .pms136-card{display:grid;gap:5px;background:#fff;border:1px solid #d8e0e7;border-left:3px solid #8a9aa8;border-radius:7px;padding:8px;cursor:grab;box-shadow:0 2px 7px rgba(30,45,60,.04)}
      .pms136-card:active{cursor:grabbing}
      .pms136-card.is-selected{outline:2px solid #7d93a8;background:#f8fafb}
      .pms136-card-head{display:flex;align-items:center;justify-content:space-between;gap:8px}
      .pms136-card-head strong{font-size:11px;color:#25384a;word-break:break-word}
      .pms136-card-head span{font-size:9px;font-weight:800;color:#51677b;background:#edf2f5;border:1px solid #d8e0e7;border-radius:999px;padding:2px 6px;white-space:nowrap}
      .pms136-card-row{display:grid;grid-template-columns:64px 1fr;gap:6px;font-size:10.5px;line-height:1.25}
      .pms136-card-row b{color:#687684}
      .pms136-card-row span{color:#263545;word-break:break-word}
      .pms136-clear{width:auto!important;margin:3px 0 0!important;padding:4px 7px!important;border:1px solid #d8e0e7!important;background:#f7f9fb!important;color:#51677b!important;border-radius:6px!important;font-size:10px!important}
      .pms136-empty{display:flex;align-items:center;justify-content:center;min-height:54px;border:1px dashed #cfd8df;border-radius:7px;color:#7a8794;font-size:11px;text-align:center;padding:8px}
      .pms136-backlogs{display:grid;grid-template-columns:1fr 1fr;gap:10px}
      .pms136-backlog{background:#fff;border:1px solid #dfe5ea;border-radius:8px;padding:10px;box-shadow:0 3px 12px rgba(30,45,60,.045)}
      .pms136-backlog header{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:8px}
      .pms136-backlog h3{margin:0;color:#25384a;font-size:13px;text-transform:uppercase}
      .pms136-backlog header span{min-width:28px;text-align:center;background:#eef3f6;border:1px solid #d8e0e7;border-radius:999px;padding:3px 8px;color:#51677b;font-size:11px;font-weight:800}
      .pms136-backlog-list{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:8px}
      #print-root .pms136-print h2{margin:5mm 0 2mm;color:#25384a;font-size:11pt;text-transform:uppercase}
      #print-root .pms136-print .print-table{width:100%;border-collapse:collapse;margin-bottom:3mm}
      #print-root .pms136-print th,#print-root .pms136-print td{border:1px solid #cfd8df;padding:1.8mm;font-size:8pt;vertical-align:top}
      #print-root .pms136-print th{background:#f1f4f6;color:#25384a}
      @media(max-width:1200px){.pms136-calendar{grid-template-columns:repeat(2,minmax(180px,1fr))}.pms136-day{min-height:260px}}
      @media(max-width:760px){.pms136-toolbar{display:grid}.pms136-actions{justify-content:flex-start}.pms136-calendar,.pms136-backlogs{grid-template-columns:1fr}.pms136-day{min-height:220px}}
      @media print{.pms136-page{display:none!important}}
    `;
  }
  function init(){
    appState();
    ensureModule();
    ensureSchemaFields();
    injectCss();
    const oldRender = render;
    render = function(){
      if (current && current.page === PAGE) {
        const content = document.getElementById("content");
        if (content) content.innerHTML = renderPlanner();
        bindPlannerActions();
        return;
      }
      return oldRender();
    };
    const oldOpenModal = typeof openModal === "function" ? openModal : null;
    if (oldOpenModal) {
      openModal = function(module, id){
        ensureSchemaFields();
        return oldOpenModal(module, id);
      };
    }
    if (typeof renderNav === "function") {
      const oldRenderNav = renderNav;
      renderNav = function(){
        ensureModule();
        return oldRenderNav();
      };
    }
  }

  init();
  window.PMS_V136_OPERATIONAL_WEEK_CALENDAR = {version: VERSION};
})();
