(function(){
  "use strict";
  const VERSION="PMS-V103-CONTRACTS-NEGOTIATIONS", CONTRACTS="contracts", DEALS="trattativeInCorso";
  const esc=v=>String(v==null?"":v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const arr=v=>Array.isArray(v)?v:[];
  const num=v=>{const n=Number(String(v==null?"":v).replace(/\s/g,"").replace(",","."));return Number.isFinite(n)?n:0;};
  const today=()=>new Date().toISOString().slice(0,10);
  const money=(v,c)=>(c||"EUR")+" "+num(v).toLocaleString("it-IT",{minimumFractionDigits:2,maximumFractionDigits:2});
  function saveState(){try{if(typeof save==="function")return save();localStorage.setItem(STORAGE_KEY,JSON.stringify(state));return true;}catch(e){console.warn(e);return false;}}
  function next(prefix,list,field){const y=new Date().getFullYear(), re=new RegExp("^"+prefix+"-"+y+"-(\\d{4})$"); const max=arr(list).reduce((a,x)=>{const m=String((field&&x[field])||x.protocol||x.code||x.id||"").match(re);return m?Math.max(a,Number(m[1])):a;},0); return prefix+"-"+y+"-"+String(max+1).padStart(4,"0");}
  function barcode(code){return typeof renderBarcode==="function"?renderBarcode(code):(typeof renderQrLite==="function"?renderQrLite(code):"<strong>"+esc(code)+"</strong>");}
  function header(title,code,sub){return typeof companyPrintHeader==="function"?companyPrintHeader(title,code,sub||""):'<div class="print-header"><div><h1>'+esc(title)+'</h1><strong>'+esc(state.settings?.legalName||"PARMITALIA DISTRIBUTION SRL")+'</strong></div><div class="print-meta"><strong>'+esc(code||"")+'</strong><br>'+esc(today())+'</div></div>';}
  function ensure(){
    window.state=window.state||{}; state.contracts=arr(state.contracts); state.contractTemplates=arr(state.contractTemplates); state.negotiations=arr(state.negotiations); state.negotiationEvents=arr(state.negotiationEvents);
    if(!state.negotiations.length && arr(state.intermediations).length){
      state.intermediations.slice(0,8).forEach(x=>state.negotiations.push({id:next("TRT",state.negotiations),sourceId:x.id,date:x.date||today(),client:x.client||"",supplier:x.supplier||"",product:x.product||"",stage:"Da qualificare",status:x.status||"Aperta",priority:x.priority||"Media",value:x.value||0,currency:x.currency||"EUR",probability:x.probability||50,owner:x.responsible||"Carlo",nextAction:x.nextAction||"Registrare prossimo passo",nextDate:x.nextDate||"",summary:x.notes||"",createdAt:new Date().toISOString()}));
    }
    if(typeof modules!=="undefined"){
      const c=modules.find(m=>m.id===CONTRACTS); if(c){c.label="Contratti";c.subtitle="Contratti visibili, modificabili e stampabili";}
      const d=modules.find(m=>m.id===DEALS); if(d){d.label="Trattative in corso";d.subtitle="Registro completo negoziazioni, eventi, schede e stampe";}
    }
  }
  function css(){if(document.getElementById("pms-v103-style"))return; const s=document.createElement("style"); s.id="pms-v103-style"; s.textContent=".pms103-page{display:grid;gap:14px}.pms103-hero{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;background:#0f2f4a;color:#fff;border-radius:8px;padding:16px 18px}.pms103-hero h3{margin:2px 0 6px;color:#fff}.pms103-hero p{margin:0;color:#dbeafe}.pms103-actions{display:flex;gap:8px;flex-wrap:wrap}.pms103-actions button{width:auto!important;margin:0!important}.pms103-card{background:#fff;border:1px solid var(--line);border-radius:8px;padding:14px}.pms103-kpis{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:10px}.pms103-kpi{border:1px solid var(--line);border-radius:8px;background:#f8fafc;padding:12px}.pms103-kpi span{display:block;color:var(--muted);font-size:11px;font-weight:900;text-transform:uppercase}.pms103-kpi strong{display:block;font-size:22px;margin-top:6px;color:#0f2f4a}.pms103-form{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:11px}.pms103-form .half{grid-column:span 2}.pms103-form .full{grid-column:1/-1}.pms103-form label{display:grid;gap:5px;font-size:12px;font-weight:800;color:var(--muted)}.pms103-form textarea{min-height:150px;line-height:1.45}.pms103-modal{position:fixed;inset:0;z-index:23000;background:rgba(15,23,42,.55);display:grid;place-items:center;padding:14px}.pms103-modal-card{width:min(1120px,96vw);max-height:94vh;overflow:auto;background:#fff;border-radius:8px;box-shadow:0 24px 70px rgba(15,23,42,.32)}.pms103-modal-head{display:flex;justify-content:space-between;align-items:center;padding:14px 16px;border-bottom:1px solid var(--line);position:sticky;top:0;background:#fff;z-index:2}.pms103-modal-body{padding:16px}.pms103-modal-actions{position:sticky;bottom:0;background:#fff;border-top:1px solid var(--line);padding:12px 16px;display:flex;justify-content:flex-end;gap:8px}.pms103-modal-actions button,.pms103-modal-head button{width:auto!important;margin:0!important}.pms103-body{white-space:pre-wrap;line-height:1.55}.pms103-event{border-left:4px solid #1f4e78;background:#f8fafc;padding:9px 11px;border-radius:6px;margin:8px 0}.pms103-status{display:inline-flex;border-radius:999px;padding:4px 9px;font-size:12px;font-weight:900;background:#eff6ff;color:#1d4ed8;border:1px solid #bfdbfe}@media(max-width:900px){.pms103-hero{display:grid}.pms103-form{grid-template-columns:1fr}.pms103-form .half{grid-column:1/-1}}@media print{@page{size:A4;margin:10mm}#print-root .pms103-print{min-height:0!important;height:auto!important;font-size:9.5pt!important;line-height:1.25!important;page-break-after:avoid!important;break-after:avoid!important}}"; document.head.appendChild(s);}
  function modal(title,body,onSave){document.getElementById("pms103-modal")?.remove(); const w=document.createElement("div"); w.id="pms103-modal"; w.className="pms103-modal"; w.innerHTML='<div class="pms103-modal-card"><div class="pms103-modal-head"><h3>'+esc(title)+'</h3><button class="secondary-button" data-close>Chiudi</button></div><div class="pms103-modal-body">'+body+'</div><div class="pms103-modal-actions"><button class="secondary-button" data-close>Annulla</button>'+(onSave?'<button class="primary-button" data-save>Salva</button>':'')+'</div></div>'; document.body.appendChild(w); w.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>w.remove()); if(onSave)w.querySelector("[data-save]").onclick=()=>onSave(w); return w;}
  function tplOptions(sel){return [''].concat(state.contractTemplates.map(t=>t.title||t.id)).map(v=>'<option '+(v===sel?'selected':'')+'>'+esc(v)+'</option>').join("");}
  function contractForm(c={}){const id=c.id||next("CTR",state.contracts); return '<div class="pms103-form"><label>Protocollo<input name="id" value="'+esc(id)+'" readonly></label><label>Tipo<input name="type" value="'+esc(c.type||"Contratto")+'"></label><label class="half">Controparte<input name="counterparty" value="'+esc(c.counterparty||"")+'"></label><label class="half">Modello<select name="template">'+tplOptions(c.template||"")+'</select></label><label>Decorrenza<input type="date" name="startDate" value="'+esc(c.startDate||"")+'"></label><label>Scadenza<input type="date" name="endDate" value="'+esc(c.endDate||"")+'"></label><label>Preavviso giorni<input type="number" name="renewalNoticeDays" value="'+esc(c.renewalNoticeDays||30)+'"></label><label>Stato<select name="status">'+["Bozza","In revisione","Da firmare","Firmato","In scadenza","Chiuso"].map(x=>'<option '+(x===(c.status||"Bozza")?'selected':'')+'>'+x+'</option>').join("")+'</select></label><label>Responsabile<input name="responsible" value="'+esc(c.responsible||(current?.user||"Carlo"))+'"></label><label class="half">Link file firmato<input name="fileLink" value="'+esc(c.fileLink||"")+'"></label><label class="full">Testo contratto<textarea name="contractBody">'+esc(c.contractBody||"")+'</textarea></label><label class="full">Note<textarea name="notes">'+esc(c.notes||"")+'</textarea></label></div>';}
  function readNamed(w,base={}){const o=Object.assign({},base); w.querySelectorAll("[name]").forEach(el=>o[el.name]=el.value); o.updatedAt=new Date().toISOString(); o.createdAt=o.createdAt||o.updatedAt; return o;}
  function editContract(id){const old=state.contracts.find(x=>x.id===id); modal(old?"Modifica contratto "+old.id:"Nuovo contratto",contractForm(old),w=>{const item=readNamed(w,old||{}); const i=state.contracts.findIndex(x=>x.id===item.id); if(i>=0)state.contracts[i]=item; else state.contracts.unshift(item); saveState(); w.remove(); render();});}
  function contractHtml(c){return '<div class="print-document pms103-print">'+header("CONTRATTO",c.id||"CTR",c.type||"")+'<table class="print-table"><tr><th>Controparte</th><td>'+esc(c.counterparty||"-")+'</td><th>Stato</th><td>'+esc(c.status||"-")+'</td></tr><tr><th>Decorrenza</th><td>'+esc(c.startDate||"-")+'</td><th>Scadenza</th><td>'+esc(c.endDate||"-")+'</td></tr><tr><th>Responsabile</th><td>'+esc(c.responsible||"-")+'</td><th>Modello</th><td>'+esc(c.template||"-")+'</td></tr></table><div class="pms103-body">'+esc(c.contractBody||c.notes||"Testo contratto non inserito.")+'</div><div style="margin-top:7mm">'+barcode(c.id||"CTR")+'</div><div class="print-footer">Contratto Parmitalia - protocollo '+esc(c.id||"CTR")+'</div></div>';}
  function viewContract(id){const c=state.contracts.find(x=>x.id===id); if(!c)return alert("Contratto non trovato."); modal("Contratto "+c.id,'<table class="print-table"><tr><th>Controparte</th><td>'+esc(c.counterparty||"-")+'</td><th>Stato</th><td>'+esc(c.status||"-")+'</td></tr><tr><th>Scadenza</th><td>'+esc(c.endDate||"-")+'</td><th>Responsabile</th><td>'+esc(c.responsible||"-")+'</td></tr></table><div class="pms103-body">'+esc(c.contractBody||c.notes||"Testo contratto non inserito.")+'</div>',null);}
  function printContract(id){const c=state.contracts.find(x=>x.id===id); if(!c)return alert("Contratto non trovato."); openPrint(contractHtml(c));}
  function renderContracts(){const signed=state.contracts.filter(c=>/firm/i.test(c.status||"")).length, exp=state.contracts.filter(c=>c.endDate&&new Date(c.endDate)>=new Date()&&((new Date(c.endDate)-new Date())/86400000)<=num(c.renewalNoticeDays||30)).length; const rows=state.contracts.map(c=>'<tr><td><span class="code-block">'+esc(c.id)+'</span></td><td><strong>'+esc(c.counterparty||"-")+'</strong><br><small>'+esc(c.type||"Contratto")+'</small></td><td>'+esc(c.startDate||"-")+'</td><td>'+esc(c.endDate||"-")+'</td><td><span class="pms103-status">'+esc(c.status||"Bozza")+'</span></td><td><button class="inline-button" data-ctr-view="'+esc(c.id)+'">Vedi</button><button class="inline-button" data-ctr-edit="'+esc(c.id)+'">Modifica</button><button class="inline-button" data-ctr-print="'+esc(c.id)+'">Stampa</button></td></tr>').join(""); return '<div class="pms103-page"><section class="pms103-hero"><div><span>CTR</span><h3>Contratti</h3><p>Archivio contratti con visualizzazione, modifica, stampa, scadenze e testi completi.</p></div><div class="pms103-actions"><button class="primary-button" data-ctr-new>+ Nuovo contratto</button><button class="secondary-button" data-nav="contractTemplates">Modelli contrattuali</button></div></section><div class="pms103-kpis"><div class="pms103-kpi"><span>Totale</span><strong>'+state.contracts.length+'</strong></div><div class="pms103-kpi"><span>Firmati</span><strong>'+signed+'</strong></div><div class="pms103-kpi"><span>In scadenza</span><strong>'+exp+'</strong></div></div><div class="pms103-card"><div class="table-wrap"><table><thead><tr><th>Protocollo</th><th>Contratto</th><th>Decorrenza</th><th>Scadenza</th><th>Stato</th><th>Azioni</th></tr></thead><tbody>'+(rows||'<tr><td colspan="6">Nessun contratto registrato.</td></tr>')+'</tbody></table></div></div></div>';}
  function dealForm(d={}){const id=d.id||next("TRT",state.negotiations); return '<div class="pms103-form"><label>Protocollo<input name="id" value="'+esc(id)+'" readonly></label><label>Data<input type="date" name="date" value="'+esc(d.date||today())+'"></label><label>Stato<select name="status">'+["Aperta","In trattativa","Campionatura","Offerta inviata","In attesa risposta","Positiva","Negativa","Sospesa"].map(x=>'<option '+(x===(d.status||"Aperta")?'selected':'')+'>'+x+'</option>').join("")+'</select></label><label>Priorita<select name="priority">'+["Alta","Media","Bassa"].map(x=>'<option '+(x===(d.priority||"Media")?'selected':'')+'>'+x+'</option>').join("")+'</select></label><label class="half">Cliente<input name="client" value="'+esc(d.client||"")+'"></label><label class="half">Fornitore<input name="supplier" value="'+esc(d.supplier||"")+'"></label><label class="half">Prodotto<input name="product" value="'+esc(d.product||"")+'"></label><label>Fase<input name="stage" value="'+esc(d.stage||"Primo contatto")+'"></label><label>Valore stimato<input type="number" name="value" value="'+esc(d.value||0)+'"></label><label>Valuta<select name="currency">'+["EUR","RON","USD"].map(x=>'<option '+(x===(d.currency||"EUR")?'selected':'')+'>'+x+'</option>').join("")+'</select></label><label>Probabilita %<input type="number" name="probability" value="'+esc(d.probability||50)+'"></label><label>Responsabile<input name="owner" value="'+esc(d.owner||(current?.user||"Carlo"))+'"></label><label class="half">Prossima azione<input name="nextAction" value="'+esc(d.nextAction||"")+'"></label><label>Data prossima azione<input type="date" name="nextDate" value="'+esc(d.nextDate||"")+'"></label><label class="full">Riepilogo trattativa<textarea name="summary">'+esc(d.summary||"")+'</textarea></label></div>';}
  function editDeal(id){const old=state.negotiations.find(x=>x.id===id); modal(old?"Modifica trattativa "+old.id:"Nuova trattativa",dealForm(old),w=>{const item=readNamed(w,old||{}); const i=state.negotiations.findIndex(x=>x.id===item.id); if(i>=0)state.negotiations[i]=item; else state.negotiations.unshift(item); saveState(); w.remove(); render();});}
  function dealEvents(id){return state.negotiationEvents.filter(e=>e.dealId===id).sort((a,b)=>String(b.date||b.createdAt).localeCompare(String(a.date||a.createdAt)));}
  function eventsHtml(id){const ev=dealEvents(id).map(e=>'<div class="pms103-event"><strong>'+esc(e.type||"Evento")+' - '+esc(e.date||e.createdAt||"")+'</strong><div>'+esc(e.text||"")+'</div><small>'+esc(e.actor||"")+(e.result?" - "+esc(e.result):"")+'</small></div>').join(""); return ev||'<div class="pms103-event">Nessun evento registrato.</div>';}
  function addEvent(id){modal("Registra evento trattativa",'<div class="pms103-form"><label>Trattativa<input name="dealId" value="'+esc(id)+'" readonly></label><label>Data<input type="datetime-local" name="date" value="'+esc(new Date().toISOString().slice(0,16))+'"></label><label>Tipo<select name="type"><option>Telefonata</option><option>Email</option><option>WhatsApp</option><option>Incontro</option><option>Offerta</option><option>Campione</option><option>Obiezione</option><option>Decisione</option><option>Nota interna</option></select></label><label>Operatore<input name="actor" value="'+esc(current?.user||"Carlo")+'"></label><label class="full">Cosa e successo<textarea name="text"></textarea></label><label class="full">Esito / prossima mossa<textarea name="result"></textarea></label></div>',w=>{const e=readNamed(w,{id:next("EVT",state.negotiationEvents),createdAt:new Date().toISOString()}); state.negotiationEvents.unshift(e); const d=state.negotiations.find(x=>x.id===id); if(d&&e.result)d.nextAction=e.result; saveState(); w.remove(); render();});}
  function viewDeal(id){const d=state.negotiations.find(x=>x.id===id); if(!d)return alert("Trattativa non trovata."); modal("Trattativa "+d.id,'<table class="print-table"><tr><th>Cliente</th><td>'+esc(d.client||"-")+'</td><th>Fornitore</th><td>'+esc(d.supplier||"-")+'</td></tr><tr><th>Prodotto</th><td>'+esc(d.product||"-")+'</td><th>Stato</th><td>'+esc(d.status||"-")+'</td></tr><tr><th>Valore</th><td>'+money(d.value,d.currency)+'</td><th>Prossima azione</th><td>'+esc(d.nextAction||"-")+'</td></tr></table><h4>Riepilogo</h4><div class="pms103-body">'+esc(d.summary||"-")+'</div><h4>Registro eventi</h4>'+eventsHtml(id),null);}
  function dealHtml(d){const ev=dealEvents(d.id).map(e=>'<tr><td>'+esc(e.date||e.createdAt||"")+'</td><td>'+esc(e.type||"")+'</td><td>'+esc(e.actor||"")+'</td><td>'+esc(e.text||"")+'</td><td>'+esc(e.result||"")+'</td></tr>').join(""); return '<div class="print-document pms103-print">'+header("SCHEDA TRATTATIVA",d.id,"Registro negoziazione")+'<table class="print-table"><tr><th>Cliente</th><td>'+esc(d.client||"-")+'</td><th>Fornitore</th><td>'+esc(d.supplier||"-")+'</td></tr><tr><th>Prodotto</th><td>'+esc(d.product||"-")+'</td><th>Stato/Fase</th><td>'+esc(d.status||"-")+' / '+esc(d.stage||"-")+'</td></tr><tr><th>Valore stimato</th><td>'+money(d.value,d.currency)+'</td><th>Probabilita</th><td>'+esc(d.probability||"0")+'%</td></tr><tr><th>Responsabile</th><td>'+esc(d.owner||"-")+'</td><th>Prossima azione</th><td>'+esc(d.nextAction||"-")+'</td></tr></table><h3>Riepilogo</h3><div class="pms103-body">'+esc(d.summary||"-")+'</div><h3>Registro eventi</h3><table class="print-table"><thead><tr><th>Data</th><th>Tipo</th><th>Operatore</th><th>Evento</th><th>Esito</th></tr></thead><tbody>'+(ev||'<tr><td colspan="5">Nessun evento.</td></tr>')+'</tbody></table><div>'+barcode(d.id)+'</div><div class="print-footer">Scheda trattativa Parmitalia - '+esc(d.id)+'</div></div>';}
  function printDeal(id){const d=state.negotiations.find(x=>x.id===id); if(!d)return alert("Trattativa non trovata."); openPrint(dealHtml(d));}
  function printPipeline(){const rows=state.negotiations.map(d=>'<tr><td>'+esc(d.id)+'</td><td>'+esc(d.client||"-")+'</td><td>'+esc(d.product||"-")+'</td><td>'+esc(d.status||"-")+'</td><td>'+money(d.value,d.currency)+'</td><td>'+esc(d.nextAction||"-")+'</td></tr>').join(""); openPrint('<div class="print-document pms103-print">'+header("REGISTRO TRATTATIVE","TRT-"+today(),"Pipeline negoziazioni")+'<table class="print-table"><thead><tr><th>ID</th><th>Cliente</th><th>Prodotto</th><th>Stato</th><th>Valore</th><th>Prossima azione</th></tr></thead><tbody>'+(rows||'<tr><td colspan="6">Nessuna trattativa.</td></tr>')+'</tbody></table><div class="print-footer">Registro trattative in corso Parmitalia</div></div>');}
  function renderDeals(){const open=state.negotiations.filter(d=>!/positiva|negativa|sospesa/i.test(d.status||"")).length, ev=state.negotiationEvents.length, due=state.negotiations.filter(d=>d.nextDate&&new Date(d.nextDate)<=new Date(Date.now()+3*86400000)).length; const rows=state.negotiations.map(d=>'<tr><td><span class="code-block">'+esc(d.id)+'</span></td><td><strong>'+esc(d.client||"-")+'</strong><br><small>'+esc(d.supplier||"-")+'</small></td><td>'+esc(d.product||"-")+'</td><td>'+esc(d.stage||"-")+'</td><td><span class="pms103-status">'+esc(d.status||"Aperta")+'</span></td><td>'+money(d.value,d.currency)+'<br><small>Prob. '+esc(d.probability||0)+'%</small></td><td>'+esc(d.nextAction||"-")+'<br><small>'+esc(d.nextDate||"")+'</small></td><td><button class="inline-button" data-deal-view="'+esc(d.id)+'">Vedi</button><button class="inline-button" data-deal-edit="'+esc(d.id)+'">Modifica</button><button class="inline-button" data-deal-event="'+esc(d.id)+'">Evento</button><button class="inline-button" data-deal-print="'+esc(d.id)+'">Stampa scheda</button></td></tr>').join(""); return '<div class="pms103-page"><section class="pms103-hero"><div><span>TRT</span><h3>Trattative in corso</h3><p>Registro reale della negoziazione: eventi, offerte, campioni, telefonate, prossime azioni e schede stampabili.</p></div><div class="pms103-actions"><button class="primary-button" data-deal-new>+ Nuova trattativa</button><button class="secondary-button" data-pipeline-print>Stampa registro</button></div></section><div class="pms103-kpis"><div class="pms103-kpi"><span>Aperte</span><strong>'+open+'</strong></div><div class="pms103-kpi"><span>Eventi registrati</span><strong>'+ev+'</strong></div><div class="pms103-kpi"><span>Azioni entro 3 giorni</span><strong>'+due+'</strong></div></div><div class="pms103-card"><div class="table-wrap"><table><thead><tr><th>Protocollo</th><th>Cliente / Fornitore</th><th>Prodotto</th><th>Fase</th><th>Stato</th><th>Valore</th><th>Prossima azione</th><th>Azioni</th></tr></thead><tbody>'+(rows||'<tr><td colspan="8">Nessuna trattativa registrata.</td></tr>')+'</tbody></table></div></div></div>';}
  function bind(){ensure(); css(); document.querySelector("[data-ctr-new]")?.addEventListener("click",()=>editContract()); document.querySelectorAll("[data-ctr-view]").forEach(b=>b.onclick=()=>viewContract(b.dataset.ctrView)); document.querySelectorAll("[data-ctr-edit]").forEach(b=>b.onclick=()=>editContract(b.dataset.ctrEdit)); document.querySelectorAll("[data-ctr-print]").forEach(b=>b.onclick=()=>printContract(b.dataset.ctrPrint)); document.querySelector("[data-deal-new]")?.addEventListener("click",()=>editDeal()); document.querySelector("[data-pipeline-print]")?.addEventListener("click",printPipeline); document.querySelectorAll("[data-deal-view]").forEach(b=>b.onclick=()=>viewDeal(b.dataset.dealView)); document.querySelectorAll("[data-deal-edit]").forEach(b=>b.onclick=()=>editDeal(b.dataset.dealEdit)); document.querySelectorAll("[data-deal-event]").forEach(b=>b.onclick=()=>addEvent(b.dataset.dealEvent)); document.querySelectorAll("[data-deal-print]").forEach(b=>b.onclick=()=>printDeal(b.dataset.dealPrint));}
  const baseRender=typeof render==="function"?render:null;
  if(baseRender&&!window.__pms103RenderWrapped){window.__pms103RenderWrapped=true; render=function(){ensure(); css(); const content=document.getElementById("content"), title=document.getElementById("page-title"), subtitle=document.getElementById("page-subtitle"); if(content&&current&&current.page===CONTRACTS){if(title)title.textContent="Contratti"; if(subtitle)subtitle.textContent="Visualizza, modifica e stampa contratti"; content.innerHTML=renderContracts(); bind(); return;} if(content&&current&&current.page===DEALS){if(title)title.textContent="Trattative in corso"; if(subtitle)subtitle.textContent="Registro completo della negoziazione"; content.innerHTML=renderDeals(); bind(); return;} const r=baseRender.apply(this,arguments); setTimeout(bind,40); return r;};}
  const baseBind=typeof bindPageActions==="function"?bindPageActions:null;
  if(baseBind&&!window.__pms103BindWrapped){window.__pms103BindWrapped=true; bindPageActions=function(){const r=baseBind.apply(this,arguments); bind(); return r;};}
  ensure(); css(); setTimeout(bind,80);
  window.pmsV103ContractsNegotiations={version:VERSION,editContract,editDeal,printDeal,printContract};
})();
