(function(){
  "use strict";

  const VERSION = "pms_v184_layout_translation_dates_supplier_stabilizer";
  const SUPPLIER_MODULE = "supplierPriceConfirmations";
  const HIDDEN_MENU_IDS = ["desktopCloudApp", "desktopRoadmap", "cryptoMonitor", "admin"];
  const FOREIGN_PAGES = ["foreignEmployees", "foreignRecruiting", "humanResources"];

  const TR = {
    EN: {
      "Scheda candidato estero":"Foreign candidate file","Privacy RO / AR - Foto passaporto":"Privacy RO / AR - Passport photo","Documento candidato estero generato dal gestionale":"Foreign candidate document generated by the system","Nome e cognome":"Full name","Nazionalita":"Nationality","Paese / citta":"Country / city","Ruolo":"Role","Telefono":"Phone","Email":"Email","Numero passaporto":"Passport number","Date passaporto":"Passport dates","File passaporto":"Passport file","Privacy caricata":"Loaded privacy","Informativa privacy - Italiano":"Privacy notice - Italian","Confidentialitate - Romana":"Privacy notice - Romanian","Privacy - AR":"Privacy - Arabic","Note documento":"Document notes","Firma candidato":"Candidate signature","Firma Parmitalia":"Parmitalia signature","Stato":"Status","Stato pratica":"Case status","Codice automatico e codice a barre":"Automatic code and barcode","Listini e conferme fornitori":"Supplier price lists and confirmations","Conferme prezzi fornitori":"Supplier price confirmations","Nuova conferma prezzo":"New price confirmation","Fornitore":"Supplier","Prodotto":"Product","Prezzo":"Price","Validita":"Validity","Azioni":"Actions","Modifica":"Edit","Elimina":"Delete","Stampa":"Print","Apri":"Open","Calendario":"Calendar","Note":"Notes","Data conferma prezzo":"Price confirmation date","Listino valido dal":"Price list valid from","Listino valido fino al":"Price list valid until","Pagamento":"Payment","Salva":"Save","Annulla":"Cancel"
    },
    RO: {
      "Scheda candidato estero":"Fisa candidat strain","Privacy RO / AR - Foto passaporto":"Confidentialitate RO / AR - Foto pasaport","Documento candidato estero generato dal gestionale":"Document candidat strain generat de aplicatie","Nome e cognome":"Nume si prenume","Nazionalita":"Nationalitate","Paese / citta":"Tara / oras","Ruolo":"Rol","Telefono":"Telefon","Email":"Email","Numero passaporto":"Numar pasaport","Date passaporto":"Date pasaport","File passaporto":"Fisier pasaport","Privacy caricata":"Confidentialitate incarcata","Informativa privacy - Italiano":"Informare confidentialitate - Italiana","Confidentialitate - Romana":"Confidentialitate - Romana","Privacy - AR":"Confidentialitate - Araba","Note documento":"Note document","Firma candidato":"Semnatura candidat","Firma Parmitalia":"Semnatura Parmitalia","Stato":"Stare","Stato pratica":"Stare dosar","Codice automatico e codice a barre":"Cod automat si cod de bare","Listini e conferme fornitori":"Liste preturi si confirmari furnizori","Conferme prezzi fornitori":"Confirmari pret furnizori","Nuova conferma prezzo":"Confirmare pret noua","Fornitore":"Furnizor","Prodotto":"Produs","Prezzo":"Pret","Validita":"Valabilitate","Azioni":"Actiuni","Modifica":"Modifica","Elimina":"Sterge","Stampa":"Printeaza","Apri":"Deschide","Calendario":"Calendar","Note":"Note","Data conferma prezzo":"Data confirmare pret","Listino valido dal":"Lista valabila de la","Listino valido fino al":"Lista valabila pana la","Pagamento":"Plata","Salva":"Salveaza","Annulla":"Anuleaza"
    },
    AR: {
      "Scheda candidato estero":"\u0645\u0644\u0641 \u0627\u0644\u0645\u0631\u0634\u062d \u0627\u0644\u0627\u062c\u0646\u0628\u064a","Privacy RO / AR - Foto passaporto":"\u0627\u0644\u062e\u0635\u0648\u0635\u064a\u0629 RO / AR - \u0635\u0648\u0631\u0629 \u062c\u0648\u0627\u0632 \u0627\u0644\u0633\u0641\u0631","Documento candidato estero generato dal gestionale":"\u0645\u0633\u062a\u0646\u062f \u0645\u0631\u0634\u062d \u0627\u062c\u0646\u0628\u064a \u062a\u0645 \u0627\u0646\u0634\u0627\u0624\u0647 \u0645\u0646 \u0627\u0644\u0646\u0638\u0627\u0645","Nome e cognome":"\u0627\u0644\u0627\u0633\u0645 \u0627\u0644\u0643\u0627\u0645\u0644","Nazionalita":"\u0627\u0644\u062c\u0646\u0633\u064a\u0629","Paese / citta":"\u0627\u0644\u0628\u0644\u062f / \u0627\u0644\u0645\u062f\u064a\u0646\u0629","Ruolo":"\u0627\u0644\u062f\u0648\u0631","Telefono":"\u0627\u0644\u0647\u0627\u062a\u0641","Email":"\u0627\u0644\u0628\u0631\u064a\u062f \u0627\u0644\u0627\u0644\u0643\u062a\u0631\u0648\u0646\u064a","Numero passaporto":"\u0631\u0642\u0645 \u062c\u0648\u0627\u0632 \u0627\u0644\u0633\u0641\u0631","Date passaporto":"\u062a\u0648\u0627\u0631\u064a\u062e \u062c\u0648\u0627\u0632 \u0627\u0644\u0633\u0641\u0631","File passaporto":"\u0645\u0644\u0641 \u062c\u0648\u0627\u0632 \u0627\u0644\u0633\u0641\u0631","Privacy caricata":"\u0627\u0644\u062e\u0635\u0648\u0635\u064a\u0629 \u0627\u0644\u0645\u062d\u0645\u0644\u0629","Informativa privacy - Italiano":"\u0627\u0634\u0639\u0627\u0631 \u0627\u0644\u062e\u0635\u0648\u0635\u064a\u0629 - \u0627\u064a\u0637\u0627\u0644\u064a","Confidentialitate - Romana":"\u0627\u0644\u062e\u0635\u0648\u0635\u064a\u0629 - \u0631\u0648\u0645\u0627\u0646\u064a","Privacy - AR":"\u0627\u0644\u062e\u0635\u0648\u0635\u064a\u0629 - \u0639\u0631\u0628\u064a","Note documento":"\u0645\u0644\u0627\u062d\u0638\u0627\u062a \u0627\u0644\u0645\u0633\u062a\u0646\u062f","Firma candidato":"\u062a\u0648\u0642\u064a\u0639 \u0627\u0644\u0645\u0631\u0634\u062d","Firma Parmitalia":"\u062a\u0648\u0642\u064a\u0639 Parmitalia","Stato":"\u0627\u0644\u062d\u0627\u0644\u0629","Stato pratica":"\u062d\u0627\u0644\u0629 \u0627\u0644\u0645\u0644\u0641","Codice automatico e codice a barre":"\u0631\u0645\u0632 \u062a\u0644\u0642\u0627\u0626\u064a \u0648\u0628\u0627\u0631\u0643\u0648\u062f","Listini e conferme fornitori":"\u0642\u0648\u0627\u0626\u0645 \u0627\u0633\u0639\u0627\u0631 \u0648\u062a\u0627\u0643\u064a\u062f\u0627\u062a \u0627\u0644\u0645\u0648\u0631\u062f\u064a\u0646","Conferme prezzi fornitori":"\u062a\u0627\u0643\u064a\u062f\u0627\u062a \u0627\u0633\u0639\u0627\u0631 \u0627\u0644\u0645\u0648\u0631\u062f\u064a\u0646","Nuova conferma prezzo":"\u062a\u0627\u0643\u064a\u062f \u0633\u0639\u0631 \u062c\u062f\u064a\u062f","Fornitore":"\u0627\u0644\u0645\u0648\u0631\u062f","Prodotto":"\u0627\u0644\u0645\u0646\u062a\u062c","Prezzo":"\u0627\u0644\u0633\u0639\u0631","Validita":"\u0627\u0644\u0635\u0644\u0627\u062d\u064a\u0629","Azioni":"\u0627\u062c\u0631\u0627\u0621\u0627\u062a","Modifica":"\u062a\u0639\u062f\u064a\u0644","Elimina":"\u062d\u0630\u0641","Stampa":"\u0637\u0628\u0627\u0639\u0629","Apri":"\u0641\u062a\u062d","Calendario":"\u0627\u0644\u062a\u0642\u0648\u064a\u0645","Note":"\u0645\u0644\u0627\u062d\u0638\u0627\u062a","Data conferma prezzo":"\u062a\u0627\u0631\u064a\u062e \u062a\u0627\u0643\u064a\u062f \u0627\u0644\u0633\u0639\u0631","Listino valido dal":"\u0642\u0627\u0626\u0645\u0629 \u0633\u0627\u0631\u064a\u0629 \u0645\u0646","Listino valido fino al":"\u0642\u0627\u0626\u0645\u0629 \u0633\u0627\u0631\u064a\u0629 \u062d\u062a\u0649","Pagamento":"\u0627\u0644\u062f\u0641\u0639","Salva":"\u062d\u0641\u0638","Annulla":"\u0627\u0644\u063a\u0627\u0621"
    }
  };

  function esc(value){ return String(value == null ? "" : value).replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c])); }
  function arr(value){ return Array.isArray(value) ? value : []; }
  function clean(value){ return String(value == null ? "" : value).replace(/\s+/g, " ").trim(); }
  function st(){
    window.state = window.state || {};
    state.settings = state.settings || {};
    if (!Array.isArray(state[SUPPLIER_MODULE])) state[SUPPLIER_MODULE] = [];
    return state;
  }
  function lang(){
    const s = st().settings || {};
    const code = s.appLanguage || s.defaultLanguage || "IT";
    return ["IT","EN","RO","AR"].includes(code) ? code : "IT";
  }
  function today(){
    const d = new Date();
    return d.getFullYear() + "-" + String(d.getMonth() + 1).padStart(2, "0") + "-" + String(d.getDate()).padStart(2, "0");
  }
  function saveNow(){
    try {
      if (typeof save === "function") save();
      else if (typeof STORAGE_KEY !== "undefined") localStorage.setItem(STORAGE_KEY, JSON.stringify(st()));
      if (window.PMS_V173_AUTO_SAVE_UPDATE && typeof window.PMS_V173_AUTO_SAVE_UPDATE.saveNow === "function") window.PMS_V173_AUTO_SAVE_UPDATE.saveNow("v184");
      return true;
    } catch(error) {
      console.warn(VERSION + " save failed", error);
      return false;
    }
  }
  function uid(prefix){
    if (typeof window.uid === "function") return window.uid(prefix);
    return prefix + "-" + Date.now().toString(36).toUpperCase();
  }
  function money(value, currency, unit){
    const n = Number(String(value || 0).replace(",", "."));
    const text = (currency || "EUR") + " " + (Number.isFinite(n) ? n.toLocaleString("it-IT", {minimumFractionDigits:2, maximumFractionDigits:4}) : clean(value));
    return unit ? text + " / " + unit : text;
  }
  function trText(value, selected){
    const code = selected || lang();
    if (code === "IT") return value;
    const dict = TR[code] || {};
    const raw = String(value == null ? "" : value);
    const text = clean(raw);
    if (!text || /^[\d\s.,:/\\()[\]%-]+$/.test(text) || /^[A-Z]{2,10}[-/][A-Z0-9-]{2,}$/i.test(text)) return value;
    if (dict[text]) return raw.replace(text, dict[text]);
    let out = text;
    Object.keys(dict).sort((a,b) => b.length - a.length).forEach(key => {
      out = out.replace(new RegExp(key.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "gi"), dict[key]);
    });
    return raw.replace(text, out);
  }
  function translateRoot(root, selected){
    const code = selected || lang();
    if (code === "IT" || !root) return;
    if (root.classList && root.classList.contains("pms184-translated-" + code)) return;
    const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, {
      acceptNode(node){
        const parent = node.parentElement;
        if (!parent || ["SCRIPT","STYLE","TEXTAREA","INPUT","SVG","CANVAS"].includes(parent.tagName)) return NodeFilter.FILTER_REJECT;
        if (parent.closest(".barcode-svg,.pms178-barcode,.pms177-barcode,svg,canvas")) return NodeFilter.FILTER_REJECT;
        return clean(node.nodeValue) ? NodeFilter.FILTER_ACCEPT : NodeFilter.FILTER_REJECT;
      }
    });
    const nodes = [];
    while (walker.nextNode()) nodes.push(walker.currentNode);
    nodes.forEach(node => { node.nodeValue = trText(node.nodeValue, code); });
    root.querySelectorAll("[placeholder],[title],[aria-label],input[type=button],input[type=submit]").forEach(el => {
      ["placeholder","title","aria-label","value"].forEach(attr => {
        if (!el.hasAttribute(attr)) return;
        el.setAttribute(attr, trText(el.getAttribute(attr), code));
      });
    });
    root.classList && root.classList.add("pms184-translated-" + code);
    root.setAttribute && root.setAttribute("lang", code.toLowerCase());
    if (code === "AR") root.setAttribute("dir", "rtl");
  }
  function preparePrintRoot(){
    const root = document.getElementById("print-root");
    if (!root) return;
    root.querySelectorAll(".print-document").forEach(doc => doc.classList.add("pms184-linear-print"));
    translateRoot(root, lang());
  }
  function installPrintHooks(){
    if (!window.__pms184PrintHooked) {
      window.__pms184PrintHooked = true;
      const basePrint = window.print;
      window.print = function(){
        preparePrintRoot();
        return basePrint.apply(this, arguments);
      };
    }
    if (typeof openPrint === "function" && !openPrint.__pms184Wrapped) {
      const base = openPrint;
      const wrapped = function(html){
        const box = document.createElement("div");
        box.innerHTML = String(html || "");
        box.querySelectorAll(".print-document").forEach(doc => doc.classList.add("pms184-linear-print"));
        translateRoot(box, lang());
        return base.call(this, box.innerHTML);
      };
      wrapped.__pms184Wrapped = true;
      try { openPrint = wrapped; window.openPrint = wrapped; } catch(error) {}
    }
  }
  function normalizeDate(value){
    const raw = clean(value);
    if (!raw) return "";
    if (/^\d{4}-\d{2}-\d{2}$/.test(raw)) return raw;
    const it = raw.match(/^(\d{1,2})[\/\-.](\d{1,2})[\/\-.](\d{4})$/);
    if (it) return it[3] + "-" + String(it[2]).padStart(2, "0") + "-" + String(it[1]).padStart(2, "0");
    return raw;
  }
  function setDateValue(input, value){
    const next = normalizeDate(value);
    input.value = next;
    input.setAttribute("value", next);
    input.dataset.pms184DateValue = next;
    input.dispatchEvent(new Event("input", {bubbles:true}));
    input.dispatchEvent(new Event("change", {bubbles:true}));
  }
  function fixDateInputs(root){
    (root || document).querySelectorAll('input[type="date"],input[type="datetime-local"]').forEach(input => {
      input.disabled = false;
      input.removeAttribute("readonly");
      input.style.pointerEvents = "auto";
      if (input.value) input.setAttribute("value", input.value);
      if (input.dataset.pms184DateBound === "1") return;
      input.dataset.pms184DateBound = "1";
      input.addEventListener("input", () => { input.setAttribute("value", input.value); input.dataset.pms184DateValue = input.value; }, true);
      input.addEventListener("change", () => { input.setAttribute("value", input.value); input.dataset.pms184DateValue = input.value; }, true);
      input.addEventListener("blur", () => { if (input.value) setDateValue(input, input.value); }, true);
      input.addEventListener("click", () => { if (typeof input.showPicker === "function") { try { input.showPicker(); } catch(error) {} } }, true);
      if (!input.parentElement.querySelector(".pms184-today-btn")) {
        const btn = document.createElement("button");
        btn.type = "button";
        btn.className = "pms184-today-btn";
        btn.textContent = "Oggi";
        btn.onclick = event => { event.preventDefault(); event.stopPropagation(); setDateValue(input, today()); };
        input.insertAdjacentElement("afterend", btn);
      }
    });
  }
  function patchDateSubmit(){
    if (typeof submitModal !== "function" || submitModal.__pms184DateWrapped) return;
    const base = submitModal;
    submitModal = function(event, module, id){
      if (event && event.target) {
        event.target.querySelectorAll('input[type="date"],input[type="datetime-local"]').forEach(input => {
          if (!input.value && input.dataset.pms184DateValue) input.value = input.dataset.pms184DateValue;
          if (input.value) input.setAttribute("value", input.value);
        });
      }
      return base.apply(this, arguments);
    };
    submitModal.__pms184DateWrapped = true;
  }
  function supplierFields(item){
    item = item || {};
    const status = ["Bozza","Richiesta inviata","Confermata","Scaduta","Annullata"];
    const currency = ["EUR","RON","USD","GBP"];
    const incoterms = ["EXW","FCA","FOB","CFR","CIF","DAP","DDP","Da definire"];
    return [
      ["supplier","Fornitore","text",true],
      ["supplierEmail","Email fornitore","email",false],
      ["product","Prodotto / articolo","text",true],
      ["articleCode","Codice articolo interno","text",false],
      ["supplierArticleCode","Codice articolo fornitore","text",false],
      ["confirmationDate","Data conferma prezzo","date",false],
      ["validFrom","Listino valido dal","date",false],
      ["validUntil","Listino valido fino al","date",true],
      ["price","Prezzo confermato","number",true],
      ["currency","Valuta","select",false,currency],
      ["unit","Unita prezzo","text",false],
      ["incoterm","Incoterm","select",false,incoterms],
      ["paymentTerms","Pagamento","text",false],
      ["status","Stato","select",false,status],
      ["notes","Note","textarea",false]
    ].map(fieldHtml.bind(null, item)).join("");
  }
  function fieldHtml(item, field){
    const [key,label,type,required,options] = field;
    const value = item[key] || "";
    const req = required ? " required" : "";
    if (type === "select") return '<label>' + esc(label) + '<select name="' + esc(key) + '"' + req + '>' + ["", ...(options || [])].map(opt => '<option value="' + esc(opt) + '"' + (opt === value ? " selected" : "") + '>' + esc(opt || "--") + '</option>').join("") + '</select></label>';
    if (type === "textarea") return '<label class="pms184-full">' + esc(label) + '<textarea name="' + esc(key) + '">' + esc(value) + '</textarea></label>';
    return '<label>' + esc(label) + '<input name="' + esc(key) + '" type="' + esc(type) + '" value="' + esc(value) + '"' + req + '></label>';
  }
  function openSupplierModal(id){
    st();
    const item = id ? arr(state[SUPPLIER_MODULE]).find(x => String(x.id) === String(id)) : null;
    const modal = document.getElementById("modal");
    const title = document.getElementById("modal-title");
    const form = document.getElementById("modal-form");
    if (!modal || !form) return;
    if (title) title.textContent = item ? "Modifica conferma prezzo" : "Nuova conferma prezzo";
    form.innerHTML = '<div class="pms184-supplier-note">Inserisci solo i dati essenziali del listino. I dettagli lunghi vanno nelle note.</div><div class="pms184-supplier-form">' + supplierFields(item || {}) + '</div><div class="form-actions"><button type="button" class="secondary-button" id="modal-cancel">Annulla</button><button type="submit" class="primary-button" style="width:auto;margin:0">Salva</button></div>';
    form.onsubmit = event => saveSupplier(event, id);
    const cancel = document.getElementById("modal-cancel");
    if (cancel) cancel.onclick = closeModal;
    modal.classList.remove("hidden");
    fixDateInputs(form);
  }
  function saveSupplier(event, id){
    event.preventDefault();
    st();
    const form = event.target;
    const data = {};
    Array.from(form.elements).forEach(el => {
      if (!el.name) return;
      data[el.name] = el.type === "number" ? Number(el.value || 0) : el.value;
    });
    data.status = data.status || "Bozza";
    data.currency = data.currency || "EUR";
    data.updatedAt = new Date().toISOString();
    if (id) {
      const index = state[SUPPLIER_MODULE].findIndex(x => String(x.id) === String(id));
      if (index >= 0) state[SUPPLIER_MODULE][index] = Object.assign({}, state[SUPPLIER_MODULE][index], data);
    } else {
      state[SUPPLIER_MODULE].unshift(Object.assign({id:uid("LST"), createdAt:new Date().toISOString()}, data));
    }
    saveNow();
    if (typeof closeModal === "function") closeModal();
    if (typeof render === "function") render();
  }
  function supplierStatus(item){
    const until = item.validUntil || "";
    if (String(item.status || "").toLowerCase().includes("scad")) return "Scaduta";
    if (until && until < today()) return "Scaduta";
    return item.status || "Bozza";
  }
  function renderSupplierPage(){
    st();
    const content = document.getElementById("content");
    const title = document.getElementById("page-title");
    const subtitle = document.getElementById("page-subtitle");
    if (title) title.textContent = "Listini e conferme fornitori";
    if (subtitle) subtitle.textContent = "Inserimento rapido e archivio prezzi fornitori";
    const search = clean((window.current && current.filters && current.filters[SUPPLIER_MODULE]) || "").toLowerCase();
    const rows = arr(state[SUPPLIER_MODULE]).filter(item => !search || JSON.stringify(item).toLowerCase().includes(search)).map(item => (
      '<tr><td><strong>' + esc(supplierStatus(item)) + '</strong></td><td>' + esc(item.supplier || "-") + '<br><small>' + esc(item.supplierEmail || "") + '</small></td><td>' + esc(item.product || "-") + '<br><small>' + esc([item.articleCode, item.supplierArticleCode].filter(Boolean).join(" / ")) + '</small></td><td><strong>' + esc(money(item.price, item.currency, item.unit)) + '</strong><br><small>' + esc(item.incoterm || "") + '</small></td><td>' + esc(item.validFrom || "-") + ' / ' + esc(item.validUntil || "-") + '</td><td>' + esc(item.notes || "-") + '</td><td><button class="inline-button" data-pms184-supplier-edit="' + esc(item.id) + '">Modifica</button><button class="inline-danger" data-pms184-supplier-delete="' + esc(item.id) + '">Elimina</button></td></tr>'
    )).join("");
    if (content) content.innerHTML = '<div class="pms184-supplier-page"><div class="section-header"><h3>Listini e conferme fornitori</h3><div class="filters"><input data-pms184-supplier-search placeholder="Cerca fornitore, prodotto, prezzo..." value="' + esc(search) + '"><button class="primary-button" style="width:auto;margin:0" data-pms184-supplier-new>+ Nuova conferma prezzo</button></div></div><div class="pms184-supplier-help">Modulo sintetico: fornitore, prodotto, date validita, prezzo, valuta, incoterm, pagamento e note. Meno confusione, piu velocita.</div><div class="table-wrap"><table class="pms184-supplier-table"><thead><tr><th>Stato</th><th>Fornitore</th><th>Prodotto</th><th>Prezzo</th><th>Validita</th><th>Note</th><th>Azioni</th></tr></thead><tbody>' + (rows || '<tr><td colspan="7" class="empty">Nessuna conferma prezzo inserita.</td></tr>') + '</tbody></table></div></div>';
    bindSupplierPage();
    translateRoot(content, lang());
  }
  function bindSupplierPage(){
    document.querySelectorAll("[data-pms184-supplier-new]").forEach(btn => btn.onclick = () => openSupplierModal(null));
    document.querySelectorAll("[data-pms184-supplier-edit]").forEach(btn => btn.onclick = () => openSupplierModal(btn.getAttribute("data-pms184-supplier-edit")));
    document.querySelectorAll("[data-pms184-supplier-delete]").forEach(btn => btn.onclick = () => {
      const id = btn.getAttribute("data-pms184-supplier-delete");
      if (!confirm("Eliminare questa conferma prezzo?")) return;
      state[SUPPLIER_MODULE] = arr(state[SUPPLIER_MODULE]).filter(item => String(item.id) !== String(id));
      saveNow();
      renderSupplierPage();
    });
    document.querySelectorAll("[data-pms184-supplier-search]").forEach(input => input.oninput = event => {
      window.current = window.current || {filters:{}};
      current.filters = current.filters || {};
      current.filters[SUPPLIER_MODULE] = event.target.value;
      renderSupplierPage();
    });
  }
  function installSupplierHooks(){
    if (typeof openModal === "function" && !openModal.__pms184SupplierWrapped) {
      const base = openModal;
      openModal = function(module, id){
        if (module === SUPPLIER_MODULE) return openSupplierModal(id || null);
        return base.apply(this, arguments);
      };
      openModal.__pms184SupplierWrapped = true;
    }
  }
  function stabilizeArchiveActions(){
    const page = window.current && current.page || "";
    if (!FOREIGN_PAGES.includes(page)) return;
    document.querySelectorAll("#content table tbody tr").forEach(row => {
      const actions = row.querySelector(".pms182-actions");
      if (!actions) return;
      const cell = actions.closest("td");
      if (!cell) return;
      cell.classList.add("pms184-stable-actions-cell");
      Array.from(cell.querySelectorAll("button")).forEach(btn => {
        if (!btn.hasAttribute("data-pms182-action")) btn.classList.add("pms184-old-action-hidden");
      });
    });
  }
  function fixMenuGaps(){
    const menu = document.getElementById("pms143-menu") || document.getElementById("nav");
    if (!menu) return;
    HIDDEN_MENU_IDS.forEach(id => {
      menu.querySelectorAll('[data-pms143-page="' + id + '"],[data-page="' + id + '"],[data-nav="' + id + '"]').forEach(node => {
        node.classList.add("pms184-menu-hidden");
        node.style.setProperty("display", "none", "important");
      });
    });
  }
  function injectCss(){
    let style = document.getElementById("pms-v184-style");
    if (!style) {
      style = document.createElement("style");
      style.id = "pms-v184-style";
      document.head.appendChild(style);
    }
    style.textContent = `
      .pms184-menu-hidden,#pms143-menu [data-pms143-page="desktopCloudApp"],#pms143-menu [data-pms143-page="desktopRoadmap"],#pms143-menu [data-pms143-page="cryptoMonitor"],#pms143-menu [data-pms143-page="admin"]{display:none!important;visibility:hidden!important;width:0!important;height:0!important;min-height:0!important;max-height:0!important;margin:0!important;padding:0!important;overflow:hidden!important}
      #pms143-menu{gap:5px!important;align-content:start!important}
      .pms184-old-action-hidden{display:none!important;visibility:hidden!important;width:0!important;height:0!important;margin:0!important;padding:0!important;overflow:hidden!important}
      .pms184-stable-actions-cell > :not(.pms182-actions){display:none!important}
      .pms184-stable-actions-cell .pms182-actions{display:flex!important;visibility:visible!important}
      .pms184-today-btn{width:auto!important;margin:0 0 0 6px!important;padding:6px 8px!important;border:1px solid #cbd5e1!important;border-radius:7px!important;background:#eef7f0!important;color:#143624!important;font-size:11px!important;font-weight:900!important}
      .pms184-supplier-help,.pms184-supplier-note{border:1px solid #d7dee8;border-left:4px solid #5f8f6d;background:#f8fafc;border-radius:8px;padding:10px 12px;margin:0 0 12px;color:#334155;font-size:12px;line-height:1.35}
      .pms184-supplier-form{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}
      .pms184-supplier-form label{display:grid;gap:4px;font-size:12px;font-weight:850;color:#475569}
      .pms184-supplier-form input,.pms184-supplier-form select,.pms184-supplier-form textarea{width:100%;box-sizing:border-box}
      .pms184-supplier-form .pms184-full{grid-column:1/-1}
      .pms184-supplier-form textarea{min-height:90px}
      .pms184-supplier-table th,.pms184-supplier-table td{vertical-align:top}
      @media(max-width:900px){.pms184-supplier-form{grid-template-columns:1fr}}
      @media print{
        @page{size:A4 portrait;margin:8mm}
        #print-root .pms184-linear-print{width:194mm!important;max-width:194mm!important;margin:0 auto!important;padding:0!important;font-size:8.4pt!important;line-height:1.18!important}
        #print-root .pms184-linear-print table.print-table:not(:has(thead)) tbody,
        #print-root .pms184-linear-print .pms182-doc-main table tbody,
        #print-root .pms184-linear-print .pms179-table table tbody{display:grid!important;grid-template-columns:1fr 1fr!important;gap:0!important;width:100%!important}
        #print-root .pms184-linear-print table.print-table:not(:has(thead)) tr,
        #print-root .pms184-linear-print .pms182-doc-main table tr,
        #print-root .pms184-linear-print .pms179-table table tr{display:grid!important;grid-template-columns:32mm minmax(0,1fr)!important;break-inside:avoid!important;page-break-inside:avoid!important}
        #print-root .pms184-linear-print th,#print-root .pms184-linear-print td{display:block!important;max-width:none!important;padding:1.2mm!important;font-size:7.8pt!important;line-height:1.14!important;overflow-wrap:anywhere!important;word-break:break-word!important}
        #print-root .pms184-linear-print .print-header,#print-root .pms184-linear-print .pms182-doc-head{display:grid!important;grid-template-columns:minmax(0,1fr) 62mm!important;gap:5mm!important}
        #print-root .pms184-linear-print h1{font-size:14pt!important;line-height:1.05!important;margin:0 0 1mm!important}
        #print-root .pms184-linear-print .pms182-privacy-block p{min-height:10mm!important;padding:1.5mm!important}
      }
    `;
  }
  function localizeVisible(){
    const code = lang();
    if (code === "IT") return;
    [document.getElementById("content"), document.getElementById("modal")].filter(Boolean).forEach(root => translateRoot(root, code));
  }
  function decorate(){
    st();
    injectCss();
    installPrintHooks();
    installSupplierHooks();
    patchDateSubmit();
    fixDateInputs(document);
    fixMenuGaps();
    stabilizeArchiveActions();
    localizeVisible();
  }

  document.addEventListener("click", event => {
    const add = event.target && event.target.closest && event.target.closest('[data-add="' + SUPPLIER_MODULE + '"]');
    if (add) {
      event.preventDefault();
      event.stopPropagation();
      if (typeof event.stopImmediatePropagation === "function") event.stopImmediatePropagation();
      openSupplierModal(null);
    }
  }, true);

  const baseRender = typeof window.render === "function" ? window.render : null;
  if (baseRender && !baseRender.__pms184Wrapped) {
    window.render = function(){
      if (window.current && current.page === SUPPLIER_MODULE) {
        renderSupplierPage();
        setTimeout(decorate, 80);
        return;
      }
      const result = baseRender.apply(this, arguments);
      setTimeout(decorate, 40);
      setTimeout(decorate, 220);
      return result;
    };
    window.render.__pms184Wrapped = true;
  }

  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", decorate);
  else decorate();
  [80, 240, 700, 1400].forEach(ms => setTimeout(decorate, ms));
  setInterval(decorate, 1200);
  window.PMS_V184_LAYOUT_TRANSLATION_DATES_SUPPLIER_STABILIZER = {version:VERSION, decorate, renderSupplierPage, openSupplierModal};
})();
