(function(){
  "use strict";

  const VERSION = "pms_v178_full_language_and_code128_barcode_fix";
  const LANGS = ["IT","EN","RO","AR"];
  const textMemory = new WeakMap();

  const CODE128 = [
    "212222","222122","222221","121223","121322","131222","122213","122312","132212","221213",
    "221312","231212","112232","122132","122231","113222","123122","123221","223211","221132",
    "221231","213212","223112","312131","311222","321122","321221","312212","322112","322211",
    "212123","212321","232121","111323","131123","131321","112313","132113","132311","211313",
    "231113","231311","112133","112331","132131","113123","113321","133121","313121","211331",
    "231131","213113","213311","213131","311123","311321","331121","312113","312311","332111",
    "314111","221411","431111","111224","111422","121124","121421","141122","141221","112214",
    "112412","122114","122411","142112","142211","241211","221114","413111","241112","134111",
    "111242","121142","121241","114212","124112","124211","411212","421112","421211","212141",
    "214121","412121","111143","111341","131141","114113","114311","411113","411311","113141",
    "114131","311141","411131","211412","211214","211232","2331112"
  ];

  const EXACT = {
    EN: {
      "Dashboard":"Dashboard","Andamenti di mercato":"Market trends","Gestione operativa":"Operations","Backoffice / Segretariato":"Back office / Secretariat","Comunicazioni / CRM":"Communications / CRM","Comunicazioni e CRM":"Communications and CRM","Comunicazioni ufficiali":"Official communications","Trattative in corso":"Current negotiations","Intermediazioni":"Intermediations","Offerte":"Offers","Offerte commerciali":"Commercial offers","Ordini":"Orders","Prodotti e Articoli":"Products and articles","Prodotti e articoli":"Products and articles","Conferme prezzi fornitori":"Supplier price confirmations","Gare e richieste":"Tenders and requests","Anagrafiche clienti e fornitori":"Customers and suppliers","Stampe":"Print center","Centro stampe":"Print center","Impostazioni":"Settings","Dipendenti estero":"Foreign employees","Recruiting estero":"Foreign recruiting","Dipendenti azienda":"Company employees","Contabilita":"Accounting","Fatturazione":"Invoicing","Banche":"Banks","Pagamenti":"Payments","Documenti":"Documents","Contratti":"Contracts","Archivio documenti":"Document archive",
      "Salva":"Save","Salva impostazioni":"Save settings","Salva modifiche":"Save changes","Modifica":"Edit","Elimina":"Delete","Stampa":"Print","Stampa scheda":"Print file","Stampa appuntamento":"Print appointment","Elimina appuntamento":"Delete appointment","Apri":"Open","Apri scheda lavoro":"Open work file","Apri calendario":"Open calendar","Chiudi":"Close","Annulla":"Cancel","Pulisci scheda":"Clear form","Nuovo":"New","Nuova scheda":"New file","Nuova scheda estero":"New foreign file","Azioni":"Actions","Calendario":"Calendar","Scheda":"File","Scheda lavoro":"Work file","Documento generato":"Generated document","Documento":"Document","Documenti da controllare":"Documents to check","Foto passaporto":"Passport photo","Passaporto":"Passport","Privacy bilingue":"Bilingual privacy","Altri documenti":"Other documents","Carica file":"Upload file","Dati trascinabili":"Draggable data","Caselle documento":"Document fields",
      "Data":"Date","Data appuntamento":"Appointment date","Data carico":"Loading date","Settimana":"Week","Oggi":"Today","Settimana precedente":"Previous week","Settimana successiva":"Next week","Stampa settimana":"Print week","Stampa tutto":"Print all","Lingua":"Language","Lingua gestionale":"App language","Lingua stampa":"Print language","Lingua stampa predefinita":"Default print language","Lingua default":"Default language",
      "Cliente":"Customer","Fornitore":"Supplier","Agente":"Agent","Prodotto":"Product","Quantita":"Quantity","Prezzo":"Price","Prezzo attuale":"Current price","Prezzo desiderato":"Target price","Valore":"Value","Importo":"Amount","Totale":"Total","Valuta":"Currency","Pagamento":"Payment","Condizioni":"Terms","Stato":"Status","Stato pratica":"Case status","Priorita":"Priority","Note":"Notes","Note interne":"Internal notes","Descrizione":"Description","Oggetto":"Subject","Destinatario":"Recipient","Protocollo":"Protocol","Data":"Date","Codice":"Code","Codice automatico":"Automatic code","Codice offerta":"Offer code","Codice a barre":"Barcode","codice a barre":"barcode","Generato da Parmitalia Management System":"Generated by Parmitalia Management System",
      "Nome":"Name","Nome completo":"Full name","Nome e cognome":"Full name","Paese":"Country","Citta":"City","Nazionalita":"Nationality","Ruolo":"Role","Profilo":"Profile","Telefono":"Phone","Telefono WhatsApp":"WhatsApp phone","Email":"Email","Canale":"Channel","Recruiter":"Recruiter","Candidato":"Candidate","Candidati extra UE trascinabili":"Draggable non-EU candidates","Candidati estero da programmare":"Foreign candidates to schedule","Nessun candidato da programmare.":"No candidate to schedule.","Appuntamento recruiting extra UE":"Non-EU recruiting appointment","Scheda candidato estero":"Foreign candidate file","Data appuntamento calendario (AAAA-MM-GG)":"Calendar appointment date (YYYY-MM-DD)",
      "Archivio dipendenti estero":"Foreign employees archive","Pratiche concluse":"Closed cases","Pratica aperta":"Open case","Pratica conclusa":"Closed case","In lavorazione":"In progress","In valutazione":"Under review","Documenti richiesti":"Documents requested","Appuntamento programmato":"Appointment scheduled","Archiviato":"Archived","Aperta":"Open","Chiuso":"Closed","Bozza":"Draft","Attivo":"Active","Da verificare":"To be checked","Da pagare":"To pay",
      "Qualita che nasce dal latte":"Quality born from milk","Parmitalia Distribution":"Parmitalia Distribution"
    },
    RO: {
      "Dashboard":"Tablou de bord","Andamenti di mercato":"Evolutii piata","Gestione operativa":"Gestiune operationala","Backoffice / Segretariato":"Backoffice / Secretariat","Comunicazioni / CRM":"Comunicari / CRM","Comunicazioni e CRM":"Comunicari si CRM","Comunicazioni ufficiali":"Comunicari oficiale","Trattative in corso":"Negocieri in curs","Intermediazioni":"Intermedieri","Offerte":"Oferte","Offerte commerciali":"Oferte comerciale","Ordini":"Comenzi","Prodotti e Articoli":"Produse si articole","Prodotti e articoli":"Produse si articole","Conferme prezzi fornitori":"Confirmari pret furnizori","Gare e richieste":"Licitatii si cereri","Anagrafiche clienti e fornitori":"Clienti si furnizori","Stampe":"Printare","Centro stampe":"Centru printare","Impostazioni":"Setari","Dipendenti estero":"Angajati strainatate","Recruiting estero":"Recrutare externa","Dipendenti azienda":"Angajati companie","Contabilita":"Contabilitate","Fatturazione":"Facturare","Banche":"Banci","Pagamenti":"Plati","Documenti":"Documente","Contratti":"Contracte","Archivio documenti":"Arhiva documente",
      "Salva":"Salveaza","Salva impostazioni":"Salveaza setarile","Salva modifiche":"Salveaza modificarile","Modifica":"Modifica","Elimina":"Sterge","Stampa":"Printeaza","Stampa scheda":"Printeaza fisa","Stampa appuntamento":"Printeaza programarea","Elimina appuntamento":"Sterge programarea","Apri":"Deschide","Apri scheda lavoro":"Deschide fisa de lucru","Apri calendario":"Deschide calendarul","Chiudi":"Inchide","Annulla":"Anuleaza","Pulisci scheda":"Goleste fisa","Nuovo":"Nou","Nuova scheda":"Fisa noua","Nuova scheda estero":"Fisa externa noua","Azioni":"Actiuni","Calendario":"Calendar","Scheda":"Fisa","Scheda lavoro":"Fisa de lucru","Documento generato":"Document generat","Documento":"Document","Documenti da controllare":"Documente de verificat","Foto passaporto":"Foto pasaport","Passaporto":"Pasaport","Privacy bilingue":"Confidentialitate bilingva","Altri documenti":"Alte documente","Carica file":"Incarca fisier","Dati trascinabili":"Date de tras","Caselle documento":"Campuri document",
      "Data":"Data","Data appuntamento":"Data programarii","Data carico":"Data incarcare","Settimana":"Saptamana","Oggi":"Azi","Settimana precedente":"Saptamana precedenta","Settimana successiva":"Saptamana urmatoare","Stampa settimana":"Printeaza saptamana","Stampa tutto":"Printeaza tot","Lingua":"Limba","Lingua gestionale":"Limba aplicatie","Lingua stampa":"Limba printare","Lingua stampa predefinita":"Limba implicita de printare","Lingua default":"Limba implicita",
      "Cliente":"Client","Fornitore":"Furnizor","Agente":"Agent","Prodotto":"Produs","Quantita":"Cantitate","Prezzo":"Pret","Prezzo attuale":"Pret actual","Prezzo desiderato":"Pret tinta","Valore":"Valoare","Importo":"Suma","Totale":"Total","Valuta":"Valuta","Pagamento":"Plata","Condizioni":"Conditii","Stato":"Stare","Stato pratica":"Stare dosar","Priorita":"Prioritate","Note":"Note","Note interne":"Note interne","Descrizione":"Descriere","Oggetto":"Subiect","Destinatario":"Destinatar","Protocollo":"Protocol","Codice":"Cod","Codice automatico":"Cod automat","Codice offerta":"Cod oferta","Codice a barre":"Cod de bare","codice a barre":"cod de bare","Generato da Parmitalia Management System":"Generat de Parmitalia Management System",
      "Nome":"Nume","Nome completo":"Nume complet","Nome e cognome":"Nume si prenume","Paese":"Tara","Citta":"Oras","Nazionalita":"Nationalitate","Ruolo":"Rol","Profilo":"Profil","Telefono":"Telefon","Telefono WhatsApp":"Telefon WhatsApp","Email":"Email","Canale":"Canal","Recruiter":"Recruiter","Candidato":"Candidat","Candidati extra UE trascinabili":"Candidati extra UE de tras","Candidati estero da programmare":"Candidati externi de programat","Nessun candidato da programmare.":"Niciun candidat de programat.","Appuntamento recruiting extra UE":"Programare recrutare extra UE","Scheda candidato estero":"Fisa candidat strain","Data appuntamento calendario (AAAA-MM-GG)":"Data programarii in calendar (AAAA-LL-ZZ)",
      "Archivio dipendenti estero":"Arhiva angajati strainatate","Pratiche concluse":"Dosare inchise","Pratica aperta":"Dosar deschis","Pratica conclusa":"Dosar inchis","In lavorazione":"In lucru","In valutazione":"In evaluare","Documenti richiesti":"Documente solicitate","Appuntamento programmato":"Programare stabilita","Archiviato":"Arhivat","Aperta":"Deschis","Chiuso":"Inchis","Bozza":"Ciorna","Attivo":"Activ","Da verificare":"De verificat","Da pagare":"De plata",
      "Qualita che nasce dal latte":"Calitate nascuta din lapte","Parmitalia Distribution":"Parmitalia Distribution"
    },
    AR: {
      "Dashboard":"لوحة التحكم","Andamenti di mercato":"اتجاهات السوق","Gestione operativa":"الإدارة التشغيلية","Backoffice / Segretariato":"المكتب الخلفي / السكرتارية","Comunicazioni / CRM":"الاتصالات / CRM","Comunicazioni e CRM":"الاتصالات و CRM","Comunicazioni ufficiali":"المراسلات الرسمية","Trattative in corso":"المفاوضات الجارية","Intermediazioni":"الوساطة","Offerte":"العروض","Offerte commerciali":"العروض التجارية","Ordini":"الطلبات","Prodotti e Articoli":"المنتجات والمواد","Prodotti e articoli":"المنتجات والمواد","Conferme prezzi fornitori":"تأكيد أسعار الموردين","Gare e richieste":"المناقصات والطلبات","Anagrafiche clienti e fornitori":"العملاء والموردون","Stampe":"الطباعة","Centro stampe":"مركز الطباعة","Impostazioni":"الإعدادات","Dipendenti estero":"الموظفون الأجانب","Recruiting estero":"التوظيف الخارجي","Dipendenti azienda":"موظفو الشركة","Contabilita":"المحاسبة","Fatturazione":"الفوترة","Banche":"البنوك","Pagamenti":"المدفوعات","Documenti":"المستندات","Contratti":"العقود","Archivio documenti":"أرشيف المستندات",
      "Salva":"حفظ","Salva impostazioni":"حفظ الإعدادات","Salva modifiche":"حفظ التعديلات","Modifica":"تعديل","Elimina":"حذف","Stampa":"طباعة","Stampa scheda":"طباعة الملف","Stampa appuntamento":"طباعة الموعد","Elimina appuntamento":"حذف الموعد","Apri":"فتح","Apri scheda lavoro":"فتح ملف العمل","Apri calendario":"فتح التقويم","Chiudi":"إغلاق","Annulla":"إلغاء","Pulisci scheda":"مسح النموذج","Nuovo":"جديد","Nuova scheda":"ملف جديد","Nuova scheda estero":"ملف خارجي جديد","Azioni":"إجراءات","Calendario":"التقويم","Scheda":"ملف","Scheda lavoro":"ملف العمل","Documento generato":"مستند منشأ","Documento":"مستند","Documenti da controllare":"مستندات للتحقق","Foto passaporto":"صورة جواز السفر","Passaporto":"جواز السفر","Privacy bilingue":"خصوصية ثنائية اللغة","Altri documenti":"مستندات أخرى","Carica file":"تحميل ملف","Dati trascinabili":"بيانات قابلة للسحب","Caselle documento":"حقول المستند",
      "Data":"التاريخ","Data appuntamento":"تاريخ الموعد","Data carico":"تاريخ التحميل","Settimana":"الأسبوع","Oggi":"اليوم","Settimana precedente":"الأسبوع السابق","Settimana successiva":"الأسبوع التالي","Stampa settimana":"طباعة الأسبوع","Stampa tutto":"طباعة الكل","Lingua":"اللغة","Lingua gestionale":"لغة النظام","Lingua stampa":"لغة الطباعة","Lingua stampa predefinita":"لغة الطباعة الافتراضية","Lingua default":"اللغة الافتراضية",
      "Cliente":"عميل","Fornitore":"مورد","Agente":"وكيل","Prodotto":"منتج","Quantita":"الكمية","Prezzo":"السعر","Prezzo attuale":"السعر الحالي","Prezzo desiderato":"السعر المستهدف","Valore":"القيمة","Importo":"المبلغ","Totale":"الإجمالي","Valuta":"العملة","Pagamento":"الدفع","Condizioni":"الشروط","Stato":"الحالة","Stato pratica":"حالة الملف","Priorita":"الأولوية","Note":"ملاحظات","Note interne":"ملاحظات داخلية","Descrizione":"الوصف","Oggetto":"الموضوع","Destinatario":"المستلم","Protocollo":"البروتوكول","Codice":"الكود","Codice automatico":"كود تلقائي","Codice offerta":"كود العرض","Codice a barre":"باركود","codice a barre":"باركود","Generato da Parmitalia Management System":"تم إنشاؤه بواسطة نظام إدارة Parmitalia",
      "Nome":"الاسم","Nome completo":"الاسم الكامل","Nome e cognome":"الاسم واللقب","Paese":"البلد","Citta":"المدينة","Nazionalita":"الجنسية","Ruolo":"الدور","Profilo":"الملف الشخصي","Telefono":"الهاتف","Telefono WhatsApp":"هاتف واتساب","Email":"البريد الإلكتروني","Canale":"القناة","Recruiter":"المسؤول عن التوظيف","Candidato":"مرشح","Candidati extra UE trascinabili":"مرشحون خارج الاتحاد الأوروبي قابلون للسحب","Candidati estero da programmare":"مرشحون أجانب للجدولة","Nessun candidato da programmare.":"لا يوجد مرشح للجدولة.","Appuntamento recruiting extra UE":"موعد توظيف خارج الاتحاد الأوروبي","Scheda candidato estero":"ملف المرشح الأجنبي","Data appuntamento calendario (AAAA-MM-GG)":"تاريخ الموعد في التقويم (YYYY-MM-DD)",
      "Archivio dipendenti estero":"أرشيف الموظفين الأجانب","Pratiche concluse":"ملفات مغلقة","Pratica aperta":"ملف مفتوح","Pratica conclusa":"ملف مغلق","In lavorazione":"قيد العمل","In valutazione":"قيد التقييم","Documenti richiesti":"المستندات المطلوبة","Appuntamento programmato":"تمت جدولة الموعد","Archiviato":"مؤرشف","Aperta":"مفتوح","Chiuso":"مغلق","Bozza":"مسودة","Attivo":"نشط","Da verificare":"للتحقق","Da pagare":"للدفع",
      "Qualita che nasce dal latte":"جودة تولد من الحليب","Parmitalia Distribution":"Parmitalia Distribution"
    }
  };

  const PHRASES = {
    EN: [
      ["Trascina il candidato nel calendario oppure apri la scheda lavoro per foto, passaporto e privacy bilingue.","Drag the candidate into the calendar or open the work file for passport photo, passport and bilingual privacy."],
      ["Gestione completa della persona estera","Complete management of the foreign person"],
      ["codice automatico e codice a barre","automatic code and barcode"],
      ["codice a barre","barcode"],["pratica lavorativa","work case"],["documentazione richiesta","required documentation"],["scheda dipendente estero","foreign employee file"],["stampa operativa completa","complete operational print"]
    ],
    RO: [
      ["Trascina il candidato nel calendario oppure apri la scheda lavoro per foto, passaporto e privacy bilingue.","Trage candidatul in calendar sau deschide fisa de lucru pentru foto pasaport, pasaport si confidentialitate bilingva."],
      ["Gestione completa della persona estera","Gestiunea completa a persoanei straine"],
      ["codice automatico e codice a barre","cod automat si cod de bare"],
      ["codice a barre","cod de bare"],["pratica lavorativa","dosar de munca"],["documentazione richiesta","documentatie solicitata"],["scheda dipendente estero","fisa angajat strain"],["stampa operativa completa","print operational complet"]
    ],
    AR: [
      ["Trascina il candidato nel calendario oppure apri la scheda lavoro per foto, passaporto e privacy bilingue.","اسحب المرشح إلى التقويم أو افتح ملف العمل لصورة جواز السفر والجواز والخصوصية ثنائية اللغة."],
      ["Gestione completa della persona estera","إدارة كاملة للشخص الأجنبي"],
      ["codice automatico e codice a barre","كود تلقائي وباركود"],
      ["codice a barre","باركود"],["pratica lavorativa","ملف العمل"],["documentazione richiesta","المستندات المطلوبة"],["scheda dipendente estero","ملف الموظف الأجنبي"],["stampa operativa completa","طباعة تشغيلية كاملة"]
    ]
  };

  const WORDS = {
    EN: {"archivio":"archive","appuntamento":"appointment","appuntamenti":"appointments","candidato":"candidate","candidati":"candidates","dipendente":"employee","dipendenti":"employees","estero":"foreign","extra":"non","ue":"EU","documento":"document","documenti":"documents","scheda":"file","schede":"files","stampa":"print","stampare":"print","modifica":"edit","elimina":"delete","apri":"open","salva":"save","calendario":"calendar","qualita":"quality","latte":"milk","nome":"name","paese":"country","citta":"city","ruolo":"role","telefono":"phone","stato":"status","note":"notes","data":"date","codice":"code","barre":"bars","privacy":"privacy","passaporto":"passport","foto":"photo","bilingue":"bilingual","pagamento":"payment","pagamenti":"payments","cliente":"customer","fornitore":"supplier","prodotto":"product","prezzo":"price","quantita":"quantity","totale":"total"},
    RO: {"archivio":"arhiva","appuntamento":"programare","appuntamenti":"programari","candidato":"candidat","candidati":"candidati","dipendente":"angajat","dipendenti":"angajati","estero":"strainatate","extra":"extra","ue":"UE","documento":"document","documenti":"documente","scheda":"fisa","schede":"fise","stampa":"printare","stampare":"printeaza","modifica":"modifica","elimina":"sterge","apri":"deschide","salva":"salveaza","calendario":"calendar","qualita":"calitate","latte":"lapte","nome":"nume","paese":"tara","citta":"oras","ruolo":"rol","telefono":"telefon","stato":"stare","note":"note","data":"data","codice":"cod","barre":"bare","privacy":"confidentialitate","passaporto":"pasaport","foto":"foto","bilingue":"bilingv","pagamento":"plata","pagamenti":"plati","cliente":"client","fornitore":"furnizor","prodotto":"produs","prezzo":"pret","quantita":"cantitate","totale":"total"},
    AR: {"archivio":"أرشيف","appuntamento":"موعد","appuntamenti":"مواعيد","candidato":"مرشح","candidati":"مرشحون","dipendente":"موظف","dipendenti":"موظفون","estero":"أجنبي","extra":"خارج","ue":"الاتحاد الأوروبي","documento":"مستند","documenti":"مستندات","scheda":"ملف","schede":"ملفات","stampa":"طباعة","stampare":"طباعة","modifica":"تعديل","elimina":"حذف","apri":"فتح","salva":"حفظ","calendario":"تقويم","qualita":"جودة","latte":"حليب","nome":"اسم","paese":"بلد","citta":"مدينة","ruolo":"دور","telefono":"هاتف","stato":"حالة","note":"ملاحظات","data":"تاريخ","codice":"كود","barre":"أشرطة","privacy":"خصوصية","passaporto":"جواز سفر","foto":"صورة","bilingue":"ثنائي اللغة","pagamento":"دفع","pagamenti":"مدفوعات","cliente":"عميل","fornitore":"مورد","prodotto":"منتج","prezzo":"سعر","quantita":"كمية","totale":"إجمالي"}
  };

  function st(){ window.state = window.state || {}; state.settings = state.settings || {}; return state; }
  function esc(value){ return String(value == null ? "" : value).replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c])); }
  function clean(value){ return String(value == null ? "" : value).replace(/\s+/g, " ").trim(); }
  function today(){ const d = new Date(); return d.getFullYear() + "-" + String(d.getMonth() + 1).padStart(2, "0") + "-" + String(d.getDate()).padStart(2, "0"); }
  function lang(kind){
    const s = st().settings;
    const code = kind === "print" ? (s.printLanguage || s.appLanguage || s.defaultLanguage) : (s.appLanguage || s.defaultLanguage);
    return LANGS.includes(code) ? code : "IT";
  }
  function saveNow(){
    try {
      if (typeof save === "function") save();
      else if (typeof STORAGE_KEY !== "undefined") localStorage.setItem(STORAGE_KEY, JSON.stringify(st()));
    } catch(error) {
      console.warn(VERSION + " save failed", error);
    }
  }
  function normalizeItalian(value){
    return clean(value)
      .replace(/[àá]/gi,"a").replace(/[èé]/gi,"e").replace(/[ìí]/gi,"i").replace(/[òó]/gi,"o").replace(/[ùú]/gi,"u")
      .replace(/ÃƒÂ /g,"a").replace(/ÃƒÂ¨|ÃƒÂ©/g,"e").replace(/ÃƒÂ¬/g,"i").replace(/ÃƒÂ²/g,"o").replace(/ÃƒÂ¹/g,"u")
      .replace(/Qualità/g,"Qualita").replace(/Quantità/g,"Quantita").replace(/città/g,"citta").replace(/Città/g,"Citta");
  }
  function shouldSkipText(value){
    const text = clean(value);
    if (!text || text.length > 900) return true;
    if (/^[\d\s.,:/\\()[\]€$%+-]+$/.test(text)) return true;
    if (/^[A-Z]{2,8}[-/][0-9A-Z-]{2,}$/i.test(text)) return true;
    if (/@|https?:|www\.|CUI|PARMITALIA DISTRIBUTION SRL/i.test(text)) return true;
    return false;
  }
  function exactLookup(text, code){
    const normalized = normalizeItalian(text);
    const dict = EXACT[code] || {};
    if (dict[normalized]) return dict[normalized];
    const noColon = normalized.replace(/\s*:\s*$/, "");
    if (dict[noColon]) return dict[noColon] + (/:$/.test(normalized) ? ":" : "");
    for (const it of Object.keys(dict)) {
      if (normalizeItalian(it).toLowerCase() === normalized.toLowerCase()) return dict[it];
    }
    for (const sourceCode of Object.keys(EXACT)) {
      const sourceDict = EXACT[sourceCode] || {};
      for (const it of Object.keys(sourceDict)) {
        if (normalizeItalian(sourceDict[it]).toLowerCase() === normalized.toLowerCase()) {
          return (dict[it] || it) + (/:$/.test(normalized) ? ":" : "");
        }
      }
    }
    return "";
  }
  function translateText(value, selected){
    const code = selected || lang();
    if (code === "IT") return value;
    if (shouldSkipText(value)) return value;
    const original = String(value);
    const leading = original.match(/^\s*/)[0];
    const trailing = original.match(/\s*$/)[0];
    let core = clean(original);
    const exact = exactLookup(core, code);
    if (exact) return leading + exact + trailing;
    let out = normalizeItalian(core);
    (PHRASES[code] || []).sort((a,b) => b[0].length - a[0].length).forEach(pair => {
      out = out.replace(new RegExp(pair[0].replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "gi"), pair[1]);
    });
    const dict = WORDS[code] || {};
    out = out.replace(/\b[A-Za-zÀ-ÿ]{3,}\b/g, word => {
      const low = normalizeItalian(word).toLowerCase();
      const translated = dict[low];
      if (!translated) return word;
      if (word === word.toUpperCase() && code !== "AR") return translated.toUpperCase();
      if (/^[A-Z]/.test(word) && code !== "AR") return translated.charAt(0).toUpperCase() + translated.slice(1);
      return translated;
    });
    return leading + out + trailing;
  }
  function walkTextNodes(root, selected, includePre){
    if (!root) return;
    const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, {
      acceptNode(node){
        const parent = node.parentElement;
        if (!parent) return NodeFilter.FILTER_REJECT;
        const tag = parent.tagName;
        if (["SCRIPT","STYLE","TEXTAREA","INPUT","SVG","CANVAS"].includes(tag)) return NodeFilter.FILTER_REJECT;
        if (!includePre && ["PRE","CODE"].includes(tag)) return NodeFilter.FILTER_REJECT;
        if (parent.closest(".barcode-svg,.pms177-barcode,.pms178-barcode,svg,canvas")) return NodeFilter.FILTER_REJECT;
        return clean(node.nodeValue) ? NodeFilter.FILTER_ACCEPT : NodeFilter.FILTER_REJECT;
      }
    });
    const nodes = [];
    while (walker.nextNode()) nodes.push(walker.currentNode);
    nodes.forEach(node => {
      if (!textMemory.has(node)) textMemory.set(node, node.nodeValue);
      const original = textMemory.get(node);
      node.nodeValue = translateText(original, selected);
    });
  }
  function translateAttributes(root, selected){
    if (!root) return;
    root.querySelectorAll("[placeholder],[title],[aria-label]").forEach(el => {
      ["placeholder","title","aria-label"].forEach(attr => {
        if (!el.hasAttribute(attr)) return;
        const key = "pms178Original" + attr.replace(/[^a-z]/gi, "");
        if (!el.dataset[key]) el.dataset[key] = el.getAttribute(attr) || "";
        el.setAttribute(attr, translateText(el.dataset[key], selected));
      });
    });
  }
  function localizePage(){
    const code = lang();
    document.documentElement.lang = code.toLowerCase();
    document.body.classList.toggle("pms178-rtl", code === "AR");
    const roots = [document.querySelector(".sidebar"), document.getElementById("content"), document.querySelector(".topbar"), document.querySelector(".modal-card"), document.querySelector(".pms176-modal"), document.querySelector(".pms175-modal")].filter(Boolean);
    roots.forEach(root => { walkTextNodes(root, code, false); translateAttributes(root, code); });
  }
  function translateHtml(html, selected){
    const code = selected || lang("print");
    if (code === "IT") return html;
    const box = document.createElement("div");
    box.innerHTML = String(html || "");
    walkTextNodes(box, code, true);
    translateAttributes(box, code);
    box.querySelectorAll(".print-document").forEach(doc => {
      doc.setAttribute("lang", code.toLowerCase());
      doc.setAttribute("dir", code === "AR" ? "rtl" : "ltr");
    });
    return box.innerHTML;
  }
  function valuesForCode128B(code){
    const cleaned = String(code || "PARMITALIA-" + today()).replace(/[^\x20-\x7F]/g, "-").slice(0, 80) || "PARMITALIA";
    const values = [104];
    for (const ch of cleaned) values.push(ch.charCodeAt(0) - 32);
    let checksum = 104;
    for (let i = 1; i < values.length; i++) checksum += values[i] * i;
    values.push(checksum % 103, 106);
    return {cleaned, values};
  }
  function renderCode128(code){
    const data = valuesForCode128B(code);
    const module = 2;
    const quiet = 18;
    const barHeight = 72;
    let x = quiet;
    let bars = "";
    data.values.forEach(value => {
      const pattern = CODE128[value] || CODE128[0];
      for (let i = 0; i < pattern.length; i++) {
        const width = Number(pattern.charAt(i)) * module;
        if (i % 2 === 0) bars += '<rect x="' + x + '" y="10" width="' + width + '" height="' + barHeight + '" fill="#111"/>';
        x += width;
      }
    });
    x += quiet;
    return '<svg class="barcode-svg pms178-barcode" width="' + x + '" height="108" viewBox="0 0 ' + x + ' 108" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Code 128 ' + esc(data.cleaned) + '"><rect width="100%" height="100%" fill="#fff"/>' + bars + '<text x="' + (x / 2) + '" y="100" text-anchor="middle" font-family="Consolas,monospace" font-size="13" fill="#111">' + esc(data.cleaned) + '</text></svg>';
  }
  function ensureBarcode(html){
    html = String(html || "").replace(/QR\s*(interno|code|archivio)?/gi, translateText("codice a barre", lang("print")));
    html = html.replace(/<div[^>]*class=["'][^"']*qr-lite[^"']*["'][\s\S]*?<\/div>/gi, match => {
      const title = (match.match(/title=["']([^"']+)["']/i) || [,"PARMITALIA"])[1];
      return renderCode128(title);
    });
    if (/barcode-svg|pms178-barcode|pms177-barcode/i.test(html)) return html;
    const codeMatch = html.match(/\b([A-Z]{2,10}[-/][0-9A-Z-]{3,})\b/i);
    const code = codeMatch ? codeMatch[1] : "PARMITALIA-" + today();
    return html.replace(/(<\/div>\s*)$/i, '<div class="pms178-auto-barcode"><strong>' + esc(translateText("Codice automatico", lang("print"))) + '</strong>' + renderCode128(code) + '</div>$1');
  }
  function installBarcode(){
    window.renderBarcode = renderCode128;
    window.renderQrLite = renderCode128;
    try { renderBarcode = renderCode128; } catch(error) {}
    try { renderQrLite = renderCode128; } catch(error) {}
  }
  function installPrint(){
    if (typeof openPrint !== "function" || openPrint.__pms178Wrapped) return;
    const base = openPrint;
    const wrapped = function(innerHtml){
      installBarcode();
      injectCss();
      const selected = lang("print");
      const translated = translateHtml(ensureBarcode(innerHtml), selected);
      return base.call(this, ensureBarcode(translated));
    };
    wrapped.__pms178Wrapped = true;
    openPrint = wrapped;
    try { window.openPrint = wrapped; } catch(error) {}
  }
  function bindLanguageSelectors(){
    document.querySelectorAll('select[name="appLanguage"],select[name="defaultLanguage"],select[name="printLanguage"],#pms134-app-lang,#pms134-print-lang,#pms136-print-lang,.pms135-print-lang').forEach(select => {
      if (select.dataset.pms178LangBound === "1") return;
      select.dataset.pms178LangBound = "1";
      select.addEventListener("change", () => {
        const value = select.value;
        if (!LANGS.includes(value)) return;
        const isPrint = /print/i.test(select.name || select.id || select.className);
        if (isPrint) st().settings.printLanguage = value;
        else {
          st().settings.appLanguage = value;
          st().settings.defaultLanguage = value;
          if (!st().settings.printLanguage) st().settings.printLanguage = value;
        }
        saveNow();
        setTimeout(localizePage, 20);
        setTimeout(localizePage, 200);
      });
    });
  }
  function injectCss(){
    let style = document.getElementById("pms-v178-style");
    if (!style) {
      style = document.createElement("style");
      style.id = "pms-v178-style";
      document.head.appendChild(style);
    }
    style.textContent = `
      body.pms178-rtl{direction:rtl;text-align:right}
      body.pms178-rtl input,body.pms178-rtl textarea,body.pms178-rtl select{text-align:right}
      .pms178-barcode{background:#fff;border:1px solid #cbd5e1;border-radius:6px;padding:4px;max-width:82mm;height:auto}
      .pms178-auto-barcode{display:grid;justify-items:center;gap:3px;margin:4mm 0;break-inside:avoid;page-break-inside:avoid}
      @media print{
        #print-root .pms178-barcode,#print-root .barcode-svg{max-width:78mm!important;width:100%!important;height:auto!important}
        #print-root .print-meta .pms178-barcode{max-width:62mm!important}
        #print-root .qr-lite,#print-root [class*="qr"]{display:none!important}
        #print-root [dir="rtl"]{direction:rtl;text-align:right}
      }
    `;
  }
  function decorate(){
    st();
    installBarcode();
    installPrint();
    injectCss();
    bindLanguageSelectors();
    localizePage();
  }

  const baseRender = typeof window.render === "function" ? window.render : null;
  if (baseRender && !baseRender.__pms178Wrapped) {
    window.render = function(){
      const result = baseRender.apply(this, arguments);
      setTimeout(decorate, 60);
      setTimeout(decorate, 220);
      return result;
    };
    window.render.__pms178Wrapped = true;
  }

  [80, 240, 700, 1400].forEach(ms => setTimeout(decorate, ms));
  setInterval(decorate, 1800);
  window.PMS_V178_FULL_LANGUAGE_AND_CODE128_BARCODE_FIX = {version:VERSION, translateText, translateHtml, renderCode128, localizePage};
})();
